import type {
  AchievementDefinition,
  BossDocketCardDefinition,
  CaseMemoryDefinition,
  CaseVariantDefinition,
  ContractStanceDefinition,
  EventDefinition,
  FieldOperationDefinition,
  LegacyDefinition,
  LongTermGoalDefinition,
  MapHotspot,
  NpcDefinition,
  ProgressionPhase,
  QuestDefinition,
  RouteMilestoneDefinition,
  RiskProfile,
  SkillDefinition,
  StoryCardDefinition,
  WeeklyGoalDefinition,
  TrainingKey,
} from './types';

export const GAME_W = 960;
export const GAME_H = 540;
export const TILE = 32;
export const MAP_TOP = 52;

export const PHASE_RULES: Record<
  ProgressionPhase,
  {
    label: string;
    line: string;
    win: { trust: number; budget: number; angerMax: number; scopeMax: number };
    partial: {
      trust: number;
      budget: number;
      angerMax: number;
      scopeMax: number;
    };
    clientIntensity: number;
    issueSeverity: number;
    rewardMultiplier: number;
    tutorialGuard: boolean;
  }
> = {
  tutorial: {
    label: '教学期',
    line: '前两单先教预算、信任、蔓延和怒气；乱点不会立刻死，但会留下可复盘的锅。',
    win: { trust: 58, budget: 38, angerMax: 94, scopeMax: 92 },
    partial: { trust: 34, budget: 20, angerMax: 100, scopeMax: 100 },
    clientIntensity: 0.52,
    issueSeverity: 0.42,
    rewardMultiplier: 0.95,
    tutorialGuard: true,
  },
  early: {
    label: '起步期',
    line: '客户开始追问，但经营重点还是把打法练出来。',
    win: { trust: 64, budget: 44, angerMax: 92, scopeMax: 90 },
    partial: { trust: 40, budget: 26, angerMax: 100, scopeMax: 98 },
    clientIntensity: 0.75,
    issueSeverity: 0.75,
    rewardMultiplier: 1,
    tutorialGuard: false,
  },
  mid: {
    label: '经营期',
    line: '每天 3 行动点开始不够用，接单、准备、训练都要取舍。',
    win: { trust: 70, budget: 50, angerMax: 88, scopeMax: 84 },
    partial: { trust: 44, budget: 30, angerMax: 100, scopeMax: 96 },
    clientIntensity: 1,
    issueSeverity: 1,
    rewardMultiplier: 1,
    tutorialGuard: false,
  },
  late: {
    label: '验收前',
    line: '旧账会回流，没清遗留就别指望 Boss 桌上没人翻截图。',
    win: { trust: 74, budget: 54, angerMax: 84, scopeMax: 80 },
    partial: { trust: 50, budget: 34, angerMax: 96, scopeMax: 94 },
    clientIntensity: 1.12,
    issueSeverity: 1.08,
    rewardMultiplier: 1.08,
    tutorialGuard: false,
  },
  boss: {
    label: '联合验收',
    line: 'Boss 会读取遗留、路线、周目标和案卷材料，三段质询不是普通客户加血。',
    win: { trust: 76, budget: 56, angerMax: 82, scopeMax: 78 },
    partial: { trust: 58, budget: 40, angerMax: 94, scopeMax: 92 },
    clientIntensity: 1.18,
    issueSeverity: 1.15,
    rewardMultiplier: 1.15,
    tutorialGuard: false,
  },
  postgame: {
    label: '周目挑战',
    line: '客户刷新且更难，但训练、路线、遗产和案卷会继续带进下一周目。',
    win: { trust: 78, budget: 58, angerMax: 80, scopeMax: 76 },
    partial: { trust: 60, budget: 42, angerMax: 92, scopeMax: 90 },
    clientIntensity: 1.28,
    issueSeverity: 1.25,
    rewardMultiplier: 1.25,
    tutorialGuard: false,
  },
};

export const RISK_PROFILE_LABELS: Record<RiskProfile, string> = {
  budget: '预算压力',
  trust: '信任缺口',
  scope: '需求蔓延',
  anger: '怒气追责',
  mixed: '复合风险',
};

export const TRAINING: Record<
  TrainingKey,
  { name: string; line: string; stat: string }
> = {
  pricing: {
    name: '报价训练',
    line: '这单咋收钱，先别玄学，先落表。',
    stat: '商业收益',
  },
  delivery: {
    name: '交付包装',
    line: '再给客户梳一遍可以，但得叫 POC。',
    stat: '信任收益',
  },
  sla: {
    name: 'SLA 边界',
    line: '再不行就拉表关单，不能永久免费续杯。',
    stat: '边界收益',
  },
  recovery: {
    name: '关门复盘',
    line: '嘴说干了也得复盘，人这辈子。',
    stat: '恢复收益',
  },
  shadow: {
    name: '影流排练',
    line: 'A 稳 B 快 C 旗舰，客户觉得选择很多。',
    stat: '隐藏路线',
  },
};

export const CONTRACT_STANCES: ContractStanceDefinition[] = [
  {
    id: 'standard',
    title: '稳态售后',
    route: 'delivery',
    unlockHint: '默认策略',
    line: '不抢钱、不硬刚，先把客户听明白。',
    clientEffect: {},
    selfEffect: {},
  },
  {
    id: 'prepaid',
    title: '商业预收款',
    route: 'business',
    unlockHint: '商业路线 20 或报价训练 Lv.1',
    line: '先收一口定金再开嗦，客户会有点冲，但现金流先活。',
    clientEffect: { budget: 8, anger: 8, trust: -3 },
    selfEffect: { cash: 90, pressure: -4 },
  },
  {
    id: 'milestone',
    title: '交付里程碑',
    route: 'delivery',
    unlockHint: '交付路线 20 或交付训练 Lv.1',
    line: '把客户愿望拆成三段验收，赢不赢都少一点扯皮。',
    clientEffect: { trust: 10, scope: -8 },
    selfEffect: { reputation: 2 },
  },
  {
    id: 'hard-boundary',
    title: '边界先行',
    route: 'boundary',
    unlockHint: '边界路线 20 或 SLA 训练 Lv.1',
    line: '开局先贴 SLA 和变更单，气氛硬一点，但锅小一点。',
    clientEffect: { scope: -14, anger: 7, budget: -4 },
    selfEffect: { boundary: 6, pressure: -6 },
  },
  {
    id: 'shadow-alt',
    title: '影流替代方案',
    route: 'shadow',
    unlockHint: '影流路线 20 或影流训练 Lv.1',
    line: 'A/B/C 三案一起抛，客户信任上来，范围也可能被撩大。',
    clientEffect: { trust: 14, scope: 8, budget: 4 },
    selfEffect: { patience: -4, cash: 35 },
  },
];

export const HOTSPOTS: Record<string, MapHotspot[]> = {
  office: [
    {
      id: 'board',
      label: '任务板',
      type: 'board',
      x: 142,
      y: 94,
      w: 108,
      h: 60,
    },
    {
      id: 'server-wall',
      label: '服务器墙巡检',
      type: 'field',
      x: 82,
      y: 184,
      w: 150,
      h: 70,
    },
    {
      id: 'meeting-room',
      label: '会议室预案',
      type: 'field',
      x: 574,
      y: 124,
      w: 220,
      h: 78,
    },
    {
      id: 'reception',
      label: '客户接待区',
      type: 'field',
      x: 288,
      y: 214,
      w: 210,
      h: 120,
    },
    {
      id: 'training',
      label: '训练台',
      type: 'training',
      x: 704,
      y: 102,
      w: 120,
      h: 64,
    },
    {
      id: 'save',
      label: '存档终端',
      type: 'save',
      x: 66,
      y: 392,
      w: 96,
      h: 56,
    },
    {
      id: 'rest',
      label: '收工复盘',
      type: 'rest',
      x: 760,
      y: 392,
      w: 112,
      h: 58,
    },
    {
      id: 'portal',
      label: '去客户现场',
      type: 'portal',
      x: 862,
      y: 238,
      w: 62,
      h: 96,
    },
  ],
  clientSite: [
    {
      id: 'portal',
      label: '回办公室',
      type: 'portal',
      x: 34,
      y: 238,
      w: 62,
      h: 96,
    },
    {
      id: 'board',
      label: '验收议程',
      type: 'board',
      x: 398,
      y: 76,
      w: 156,
      h: 58,
    },
    {
      id: 'procurement-table',
      label: '采购桌攻防',
      type: 'field',
      x: 665,
      y: 174,
      w: 210,
      h: 88,
    },
    {
      id: 'security-corner',
      label: '安全合规角',
      type: 'field',
      x: 778,
      y: 386,
      w: 146,
      h: 76,
    },
    {
      id: 'big-screen',
      label: '大屏演示彩排',
      type: 'field',
      x: 574,
      y: 82,
      w: 220,
      h: 120,
    },
    {
      id: 'save',
      label: '会议存档',
      type: 'save',
      x: 808,
      y: 394,
      w: 102,
      h: 56,
    },
  ],
};

export const FIELD_OPERATIONS: FieldOperationDefinition[] = [
  {
    id: 'server-preflight',
    title: '服务器墙：预检告警',
    mapId: 'office',
    hotspotId: 'server-wall',
    route: 'boundary',
    cost: 1,
    unlockHint: '办公室服务器墙，每天可巡检一次。',
    line: '博哥盯着监控灯，先把可能炸的地方圈出来。巡检不帅，但少背锅。',
    successLine:
      '告警被提前降级，压力少一截；如果有 SLA/压力旧账，会顺手清一个。',
    effect: { pressure: -10, boundary: 4, energy: -4 },
    xp: 12,
    routeGain: 6,
    clearIssueType: 'sla',
    unlock: () => true,
  },
  {
    id: 'server-cost-snapshot',
    title: '服务器墙：成本快照',
    mapId: 'office',
    hotspotId: 'server-wall',
    route: 'business',
    cost: 1,
    unlockHint: '完成 GPU 账单或现金低时出现。',
    line: '博哥从资源曲线里扒出空转、峰值、预留三列，准备下次把“云很贵”讲成人话。',
    successLine: '成本快照进案卷，下一次预算质疑不会只靠嘴硬顶。',
    effect: { cash: 70, pressure: -4, energy: -5 },
    xp: 14,
    routeGain: 7,
    clearIssueType: 'budget',
    relationshipQuestId: 'gpu',
    relationshipGain: 4,
    unlock: (state) =>
      state.completed.includes('gpu') ||
      state.stats.cash < 700 ||
      state.issues.some((issue) => issue.type === 'budget'),
  },
  {
    id: 'meeting-boss-rehearsal',
    title: '会议室：联合验收彩排',
    mapId: 'office',
    hotspotId: 'meeting-room',
    route: 'delivery',
    cost: 1,
    unlockHint: '完成 3 个客户后可彩排。',
    line: '博哥把报价表、验收表、SLA 表摆到会议桌上，先自己审自己。',
    successLine: '彩排抓出一处漏洞，Boss 桌上的信任缺口会少一点。',
    effect: { reputation: 4, patience: -3, pressure: -8 },
    xp: 16,
    routeGain: 7,
    clearIssueType: 'delivery',
    unlock: (state) =>
      state.completed.filter((id) => id !== 'boss').length >= 3,
  },
  {
    id: 'meeting-scope-trim',
    title: '会议室：需求裁剪会',
    mapId: 'office',
    hotspotId: 'meeting-room',
    route: 'boundary',
    cost: 1,
    unlockHint: '有需求蔓延或合规/交付旧账时出现。',
    line: '博哥把“顺手”拆成能做、不能做、加钱做，先在白板上把幻想剪短。',
    successLine: '需求被裁掉一圈，但客户会觉得博哥突然没那么好说话。',
    effect: { boundary: 8, reputation: -2, pressure: -8 },
    xp: 14,
    routeGain: 8,
    clearIssueType: 'delivery',
    unlock: (state) =>
      state.issues.some(
        (issue) => issue.type === 'delivery' || issue.type === 'compliance',
      ) || state.routes.boundary >= 25,
  },
  {
    id: 'reception-trust-call',
    title: '接待区：老客户回访',
    mapId: 'office',
    hotspotId: 'reception',
    route: 'delivery',
    cost: 1,
    unlockHint: '至少完成 1 个客户后出现。',
    line: '博哥给老客户补一句人话：不是不管，是下次别把 POC 念成全量上线。',
    successLine: '客户关系升温，口碑像小火苗一样往上窜。',
    effect: { reputation: 5, patience: -3 },
    xp: 12,
    routeGain: 5,
    relationshipQuestId: 'agent',
    relationshipGain: 8,
    unlock: (state) =>
      state.completed.filter((id) => id !== 'boss').length >= 1,
  },
  {
    id: 'reception-refuse-script',
    title: '接待区：拒单话术排练',
    mapId: 'office',
    hotspotId: 'reception',
    route: 'boundary',
    cost: 1,
    unlockHint: 'SLA 训练 Lv.1 或边界路线 20 后出现。',
    line: '博哥把“这不行”练成“这项进变更单”，拒绝也得像产品经理。',
    successLine: '拒绝话术变得没那么伤人，边界感上涨。',
    effect: { boundary: 7, patience: 3, pressure: -3 },
    xp: 12,
    routeGain: 6,
    unlock: (state) => state.training.sla >= 1 || state.routes.boundary >= 20,
  },
  {
    id: 'procurement-anchor',
    title: '采购桌：报价锚点攻防',
    mapId: 'clientSite',
    hotspotId: 'procurement-table',
    route: 'business',
    cost: 1,
    unlockHint: '客户现场，商业路线 20 或现金低时出现。',
    line: '采购姐准备砍价，博哥先把基础、加急、旗舰三档摊开。',
    successLine: '报价锚点立住，下一次砍价不会直接砍到地板。',
    effect: { cash: 120, pressure: 2, boundary: 2 },
    xp: 16,
    routeGain: 9,
    clearIssueType: 'budget',
    relationshipQuestId: 'invoice',
    relationshipGain: 5,
    unlock: (state) =>
      state.routes.business >= 20 ||
      state.stats.cash < 800 ||
      state.completed.includes('invoice'),
  },
  {
    id: 'procurement-rival-counter',
    title: '采购桌：友商低价反制',
    mapId: 'clientSite',
    hotspotId: 'procurement-table',
    route: 'shadow',
    cost: 1,
    unlockHint: '第三天后或影流路线 20 后出现。',
    line: '友商把低价甩上桌，ShadowBo 递出三张风险对照表。',
    successLine: '客户终于看见低价后面的空洞，影流路线推进。',
    effect: { reputation: 4, patience: -4, pressure: -4 },
    xp: 18,
    routeGain: 9,
    issue: { label: '友商低价回声', type: 'budget', severity: 5 },
    unlock: (state) => state.day >= 3 || state.routes.shadow >= 20,
  },
  {
    id: 'security-evidence-pack',
    title: '安全角：合规证据包',
    mapId: 'clientSite',
    hotspotId: 'security-corner',
    route: 'boundary',
    cost: 1,
    unlockHint: '有合规旧账或第三幕后出现。',
    line: '博哥把审计、脱敏、例外说明合成一包证据，免得材料自己下崽。',
    successLine: '合规旧账被压住，Boss 桌上少一张红字。',
    effect: { boundary: 7, pressure: -9, energy: -4 },
    xp: 18,
    routeGain: 9,
    clearIssueType: 'compliance',
    relationshipQuestId: 'security',
    relationshipGain: 6,
    unlock: (state) =>
      state.chapter >= 3 ||
      state.issues.some((issue) => issue.type === 'compliance'),
  },
  {
    id: 'bigscreen-demo-script',
    title: '大屏：演示剧本彩排',
    mapId: 'clientSite',
    hotspotId: 'big-screen',
    route: 'delivery',
    cost: 1,
    unlockHint: '完成 Agent 或直播客户后出现。',
    line: '博哥把大屏演示从“震撼一点”改成“按场景跑通”。',
    successLine: '演示不再靠玄学，交付信任上涨。',
    effect: { reputation: 6, patience: -3, pressure: -5 },
    xp: 16,
    routeGain: 8,
    clearIssueType: 'delivery',
    relationshipQuestId: 'live',
    relationshipGain: 6,
    unlock: (state) =>
      state.completed.includes('agent') ||
      state.completed.includes('live') ||
      state.stats.reputation >= 55,
  },
  {
    id: 'bigscreen-shadow-storyboard',
    title: '大屏：影流分镜',
    mapId: 'clientSite',
    hotspotId: 'big-screen',
    route: 'shadow',
    cost: 1,
    unlockHint: '影流训练 Lv.1 后出现。',
    line: 'ShadowBo 把 A/B/C 三案投到大屏：稳态版、快速版、旗舰版，全都不是白送。',
    successLine: '影流分镜进入 Boss 材料，客户以为自己选择很多。',
    effect: { patience: -5, cash: 90, pressure: -4 },
    xp: 20,
    routeGain: 10,
    relationshipQuestId: 'shadow',
    relationshipGain: 6,
    unlock: (state) => state.training.shadow >= 1 || state.routes.shadow >= 30,
  },
];

export const NPCS: NpcDefinition[] = [
  {
    id: 'npc-gpu',
    name: 'GPU 账单客户',
    role: '账单爆炸',
    mapId: 'office',
    x: 330,
    y: 270,
    tint: 0x2f6fbe,
    questId: 'gpu',
  },
  {
    id: 'npc-agent',
    name: '灵感老板',
    role: 'Agent 上线',
    mapId: 'office',
    x: 492,
    y: 330,
    tint: 0x2d9d73,
    questId: 'agent',
  },
  {
    id: 'npc-sla',
    name: '体验官',
    role: '两秒追责',
    mapId: 'office',
    x: 640,
    y: 250,
    tint: 0xb16a2c,
    questId: 'sla',
  },
  {
    id: 'npc-private',
    name: '合规客户',
    role: '私有化',
    mapId: 'clientSite',
    x: 266,
    y: 250,
    tint: 0x7b62b5,
    questId: 'private',
  },
  {
    id: 'npc-cost',
    name: '运营总监',
    role: '成本治理',
    mapId: 'clientSite',
    x: 458,
    y: 322,
    tint: 0x3289a0,
    questId: 'cost',
  },
  {
    id: 'npc-shadow',
    name: '采购委员会',
    role: '影流方案',
    mapId: 'clientSite',
    x: 650,
    y: 252,
    tint: 0x3f3159,
    questId: 'shadow',
  },
  {
    id: 'npc-voicebot',
    name: '客服负责人',
    role: 'AI 客服',
    mapId: 'office',
    x: 196,
    y: 318,
    tint: 0x4b8ec9,
    questId: 'voicebot',
  },
  {
    id: 'npc-quota',
    name: '算力采购',
    role: 'GPU 配额',
    mapId: 'office',
    x: 732,
    y: 318,
    tint: 0xbd7d2f,
    questId: 'quota',
  },
  {
    id: 'npc-migration',
    name: '迁移经理',
    role: '跨云迁移',
    mapId: 'office',
    x: 548,
    y: 232,
    tint: 0x4b6bbd,
    questId: 'migration',
  },
  {
    id: 'npc-live',
    name: '直播老板',
    role: '直播峰值',
    mapId: 'office',
    x: 450,
    y: 410,
    tint: 0x2f9a8a,
    questId: 'live',
  },
  {
    id: 'npc-security',
    name: '安全审计',
    role: '渗透测试',
    mapId: 'clientSite',
    x: 184,
    y: 330,
    tint: 0xa34f52,
    questId: 'security',
  },
  {
    id: 'npc-invoice',
    name: '财务结算',
    role: '发票合同',
    mapId: 'clientSite',
    x: 350,
    y: 392,
    tint: 0xa98c35,
    questId: 'invoice',
  },
  {
    id: 'npc-datapack',
    name: '数据团队',
    role: '知识库导入',
    mapId: 'clientSite',
    x: 588,
    y: 374,
    tint: 0x3b8f62,
    questId: 'datapack',
  },
  {
    id: 'npc-vip',
    name: 'VIP 老板席',
    role: '专属大客户',
    mapId: 'clientSite',
    x: 744,
    y: 220,
    tint: 0x8b4ac4,
    questId: 'vip',
  },
  {
    id: 'npc-boss',
    name: '联合验收组',
    role: 'Boss',
    mapId: 'clientSite',
    x: 488,
    y: 166,
    tint: 0x8e334d,
    questId: 'boss',
  },
];

export const QUESTS: QuestDefinition[] = [
  {
    id: 'gpu',
    title: 'GPU 账单爆炸',
    client: '财务凝视的 GPU 团队',
    mapId: 'office',
    npcId: 'npc-gpu',
    route: 'business',
    recommendedLevel: 1,
    cost: 1,
    reward: 230,
    xp: 50,
    intro:
      '财务姐拿着云账单问：这咋收钱啊？博哥寻思，账单可以再梳一遍，但不能白梳到天亮。',
    winLine: '收钱这事终于从玄学变成表格了。',
    partialLine: '售后梳了一遍，头发没少，需求少了一点。',
    failLine: '财务截图一进群，博哥心率开始上云。',
    issue: { label: '预算质疑', type: 'budget', severity: 9 },
    enemy: { anger: 30, budget: 64, scope: 40, trust: 38 },
    chapter: 1,
    tier: 'tutorial',
    riskProfile: 'budget',
    teachingHint:
      '第一单教“预算不是怒吼出来的”：先用账单和报价守预算，再用 POC/边界收需求。',
    recommendedPlan: ['report', 'anchor', 'poc', 'contract'],
    arc: '第一幕：免费售后的入口',
    objective: '把“顺手看账单”改成可收费的成本治理。',
    traits: ['预算敏感', '会拿截图追问', '报价类技能收益更高'],
    preferred: ['pricing', 'recovery'],
    resistance: { trust: -2 },
    phaseLines: [
      '财务姐翻出旧截图：你上次不是还能送吗？',
      '预算表一亮，客户开始问每一块 GPU 跑哪去了。',
    ],
    unlock: () => true,
  },
  {
    id: 'agent',
    title: 'AI Agent 今天上线',
    client: '灵感爆棚的老板',
    mapId: 'office',
    npcId: 'npc-agent',
    route: 'delivery',
    recommendedLevel: 1,
    cost: 1,
    reward: 250,
    xp: 54,
    intro:
      '老板姐说 Agent 今天就要上线，还顺手接 CRM、客服和日报。博哥问：这单咋收钱啊？',
    winLine: '免费售后到这儿，后面每一步都有名字也有价格。',
    partialLine: '客户点头了，但点得像留了三页补充意见。',
    failLine: '博哥嘴都说干了，客户还是觉得顺手等于免费。',
    issue: { label: '交付质疑', type: 'delivery', severity: 8 },
    enemy: { anger: 28, budget: 62, scope: 46, trust: 36 },
    chapter: 1,
    tier: 'tutorial',
    riskProfile: 'scope',
    teachingHint:
      '第二单教“顺手会长腿”：先 POC 拉信任，再用边界把今天上线拆成阶段。',
    recommendedPlan: ['poc', 'report', 'contract', 'anchor'],
    arc: '第一幕：免费售后的入口',
    objective: '把“今天上线”拆成 POC、验收和排期。',
    traits: ['需求蔓延快', '信任缺口大', '交付类技能收益更高'],
    preferred: ['delivery'],
    resistance: { budget: -2 },
    phaseLines: [
      '老板姐一句“顺手接 CRM”，会议室温度直接上云。',
      '客户把 POC 说成全量上线，博哥开始找表。',
    ],
    unlock: () => true,
  },
  {
    id: 'sla',
    title: '两秒延迟也算事故',
    client: '冷静追问的体验官',
    mapId: 'office',
    npcId: 'npc-sla',
    route: 'boundary',
    recommendedLevel: 1,
    cost: 1,
    reward: 240,
    xp: 52,
    intro:
      '体验姐把慢两秒叫事故，说不行你再补一次说明。博哥把说明摊开：姐，补可以，SLA 得收口。',
    winLine: '边界一落表，会议室空气都降噪了。',
    partialLine: '这不算赢，但至少没白陪笑。',
    failLine: '合同没说话，群聊先开庭了。',
    issue: { label: 'SLA 追责', type: 'sla', severity: 10 },
    enemy: { anger: 32, budget: 60, scope: 44, trust: 38 },
    chapter: 1,
    tier: 'early',
    riskProfile: 'anger',
    teachingHint:
      '第三单开始有追责压力：怒气高时别硬报价，先降级预案或合同边界止血。',
    recommendedPlan: ['contract', 'poc', 'report', 'anchor'],
    arc: '第一幕：免费售后的入口',
    objective: '把“两秒事故”收回 SLA 边界。',
    traits: ['怒气上升快', '边界不足会被追责', 'SLA 训练收益更高'],
    preferred: ['sla'],
    resistance: { anger: -2 },
    phaseLines: [
      '体验姐把两秒延迟念了三遍，像在念判决书。',
      '群聊开始开庭，博哥寻思这 b 班非上不可吗。',
    ],
    unlock: () => true,
  },
  {
    id: 'private',
    title: '私有化合规全都要',
    client: '深不可测的合规客户',
    mapId: 'clientSite',
    npcId: 'npc-private',
    route: 'boundary',
    recommendedLevel: 2,
    cost: 1,
    reward: 330,
    xp: 66,
    intro:
      '合规姐只说离线可用，后面跟着审计、权限、脱敏、部署文档。再梳一遍可以，材料不能免费下崽。',
    winLine: '姐，云不是不要钱，云只是花钱比较有礼貌。',
    partialLine: '基础版成交，旗舰版幻想暂时封存。',
    failLine: '这单没收住，需求从门缝里长出来了。',
    issue: { label: '合规补材料', type: 'compliance', severity: 12 },
    enemy: { anger: 44, budget: 52, scope: 72, trust: 20 },
    chapter: 2,
    tier: 'mid',
    riskProfile: 'scope',
    teachingHint:
      '合规客户会把“离线可用”扩成材料宇宙；先压蔓延，再补信任。',
    recommendedPlan: ['contract', 'milestone', 'poc', 'report'],
    arc: '第二幕：客户学会复用顺手一下',
    objective: '让私有化、审计、脱敏和部署文档分别进报价。',
    traits: ['蔓延极高', '合同边界更关键', '口头承诺效果打折'],
    preferred: ['sla', 'delivery'],
    resistance: { scope: 3, anger: -3 },
    phaseLines: [
      '合规姐说“离线可用”只有四个字，后面拖着一车材料。',
      '旧 SLA 问题被翻出来，客户问：上次都认了，这次咋不认？',
    ],
    unlock: (state) =>
      state.completed.includes('sla') ||
      state.completed.includes('agent') ||
      state.issues.some((issue) =>
        ['sla', 'compliance', 'delivery'].includes(issue.type),
      ) ||
      state.completed.filter((id) => id !== 'boss').length >= 2,
    advanced: true,
  },
  {
    id: 'cost',
    title: '成本治理日报免费吗',
    client: '拿着 Excel 的运营总监',
    mapId: 'clientSite',
    npcId: 'npc-cost',
    route: 'business',
    recommendedLevel: 2,
    cost: 1,
    reward: 310,
    xp: 62,
    intro:
      '运营姐要日报、预警、阈值，还问这不是默认的吗。博哥：可以再梳一遍账单，但梳头也得收钱啊。',
    winLine: '这单梳明白了，账单也终于像个人话。',
    partialLine: '先收一半，剩下的边界明天继续捞。',
    failLine: '报价没锚住，售后直接变成无限续杯。',
    issue: { label: '免费期待', type: 'budget', severity: 11 },
    enemy: { anger: 46, budget: 44, scope: 66, trust: 24 },
    chapter: 2,
    tier: 'mid',
    riskProfile: 'budget',
    teachingHint:
      '成本日报的核心不是解释，是套餐化；预算掉太低就先报表再锚价。',
    recommendedPlan: ['report', 'anchor', 'contract', 'review'],
    arc: '第二幕：客户学会复用顺手一下',
    objective: '把日报、阈值和预警分成套餐，别让免费续杯成习惯。',
    traits: ['预算压力高', '会吃报价锚定', '失败会拖出财务追杀'],
    preferred: ['pricing', 'recovery'],
    resistance: { budget: 2 },
    phaseLines: [
      '运营姐打开 Excel：这个字段也顺手加一下呗。',
      '财务旧截图进场，客户开始相信免费是传统艺能。',
    ],
    unlock: (state) =>
      state.completed.includes('gpu') ||
      state.issues.some((issue) => issue.type === 'budget') ||
      state.completed.filter((id) => id !== 'boss').length >= 2,
    advanced: true,
  },
  {
    id: 'shadow',
    title: '影流三方案采购会',
    client: '选择困难的采购委员会',
    mapId: 'clientSite',
    npcId: 'npc-shadow',
    route: 'shadow',
    recommendedLevel: 3,
    cost: 1,
    reward: 340,
    xp: 70,
    intro:
      '采购姐嫌一个报价太硬，要不再来一版？博哥影流启动：A 稳，B 快，C 看着牛逼嗷。',
    winLine: '影流 Bo 同时递出三套方案，客户获得了被尊重的幻觉。',
    partialLine: '客户选了 B 方案，但 A 和 C 的幻想还在会议室飘。',
    failLine: '三个 Bo 互相补充，需求复杂度原地升天。',
    issue: { label: '方案内耗', type: 'pressure', severity: 12 },
    enemy: { anger: 38, budget: 54, scope: 76, trust: 26 },
    chapter: 2,
    tier: 'mid',
    riskProfile: 'mixed',
    teachingHint:
      '影流三案能拉信任也会撩大范围；没有边界时别把三案开成免费菜单。',
    recommendedPlan: ['shadow', 'poc', 'contract', 'anchor'],
    arc: '第二幕：客户学会复用顺手一下',
    objective: '用 A/B/C 三套方案把选择权交给客户，把价格留给自己。',
    traits: ['选择困难', '影流收益高但会刺激范围', '路线分影响结局'],
    preferred: ['shadow', 'pricing'],
    resistance: { trust: 3, scope: 2 },
    phaseLines: [
      '采购姐说一个方案太硬，三个方案太贵，两个方案又像没诚意。',
      'ShadowBo 在脑内递表：A 稳，B 快，C 旗舰，全都不是白送。',
    ],
    unlock: (state) =>
      state.training.shadow > 0 ||
      state.routes.shadow >= 18 ||
      state.completed.includes('cost') ||
      state.completed.length >= 3,
    advanced: true,
  },
  {
    id: 'voicebot',
    title: 'AI 客服夜里胡说',
    client: '被机器人折磨的客服负责人',
    mapId: 'office',
    npcId: 'npc-voicebot',
    route: 'delivery',
    recommendedLevel: 2,
    cost: 1,
    reward: 285,
    xp: 58,
    intro:
      '客服姐说机器人半夜把退款讲成赠品，客户群炸了。博哥寻思，Agent 能上线，护栏也得收钱。',
    winLine: '夜间话术被加上护栏，机器人终于不像喝多了。',
    partialLine: '先把高危词挡住，但知识库还在漏风。',
    failLine: 'AI 客服继续胡说，客服姐开始怀疑博哥也是模型生成的。',
    issue: { label: '话术失控', type: 'delivery', severity: 9 },
    enemy: { anger: 52, budget: 48, scope: 66, trust: 18 },
    chapter: 2,
    tier: 'mid',
    riskProfile: 'trust',
    teachingHint:
      'AI 客服翻车先补信任，别一上来谈钱；案例、护栏、灰度比嘴硬有用。',
    recommendedPlan: ['poc', 'demo', 'fallback', 'review'],
    arc: '第二幕：AI 上线不是许愿池',
    objective: '把“机器人胡说”拆成护栏、知识库和灰度验收。',
    traits: ['信任低', '需求会扩成知识库治理', '交付路线能快速止血'],
    preferred: ['delivery', 'recovery'],
    resistance: { trust: 2, scope: 1 },
    phaseLines: [
      '客服姐贴出夜间对话：AI 说得挺自信，错得也挺稳定。',
      '客户问能不能顺手接投诉工单，博哥手已经摸到验收表。',
    ],
    unlock: (state) =>
      state.completed.includes('agent') ||
      state.training.delivery >= 1 ||
      state.cycle >= 2,
    advanced: true,
  },
  {
    id: 'quota',
    title: 'H200 配额插队',
    client: '急着训练大模型的算力采购',
    mapId: 'office',
    npcId: 'npc-quota',
    route: 'business',
    recommendedLevel: 3,
    cost: 1,
    reward: 390,
    xp: 74,
    intro:
      '采购姐说训练明天开跑，GPU 今天必须到位，还问老客户能不能插个队。博哥：插队可以，价格先排队。',
    winLine: '配额被拆成预留费、加急费和排期风险，算力终于不靠感情调度。',
    partialLine: '先拿到一半配额，剩下的靠预收款续命。',
    failLine: '配额没锚住，客户觉得云上资源应该像空气一样免费。',
    issue: { label: '算力插队', type: 'budget', severity: 12 },
    enemy: { anger: 48, budget: 38, scope: 62, trust: 26 },
    chapter: 2,
    tier: 'late',
    riskProfile: 'budget',
    teachingHint:
      '算力插队是预算战，报价阶梯和预收款会比免费协调更稳。',
    recommendedPlan: ['anchor', 'ladder', 'report', 'contract'],
    arc: '第二幕：AI 热潮开始抢资源',
    objective: '把 GPU 插队改成可收费的配额预留和加急排期。',
    traits: ['预算低', '商业预收收益高', '失败会推高维护债'],
    preferred: ['pricing', 'sla'],
    resistance: { budget: 3 },
    phaseLines: [
      '采购姐说 H200 不够可以协调，博哥听见协调两个字就想报价。',
      '客户开始比较友商低价，预算条肉眼可见地往下掉。',
    ],
    unlock: (state) =>
      state.completed.includes('gpu') &&
      (state.routes.business >= 18 || state.cycle >= 2),
    advanced: true,
  },
  {
    id: 'migration',
    title: '跨云迁移三天完成',
    client: '被 Deadline 追着跑的迁移经理',
    mapId: 'office',
    npcId: 'npc-migration',
    route: 'boundary',
    recommendedLevel: 3,
    cost: 1,
    reward: 360,
    xp: 72,
    intro:
      '迁移姐说三天从友商云搬过来，最好不停机、不改代码、不加钱。博哥沉默两秒：这不是迁移，这是许愿。',
    winLine: '迁移被拆成评估、演练、割接窗口，三天神话变成三段合同。',
    partialLine: '先搬非核心链路，核心系统留给下一个窗口。',
    failLine: '迁移窗口没守住，客户把停机也算到售后头上。',
    issue: { label: '割接追责', type: 'sla', severity: 13 },
    enemy: { anger: 50, budget: 46, scope: 76, trust: 20 },
    chapter: 2,
    tier: 'late',
    riskProfile: 'scope',
    teachingHint:
      '迁移三天完成是边界战，先把演练和回滚写出来，再谈交付。',
    recommendedPlan: ['contract', 'milestone', 'fallback', 'poc'],
    arc: '第二幕：顺手开始搬家',
    objective: '把三天迁移拆成演练、窗口和回滚预案。',
    traits: ['蔓延极高', '边界先行能压风险', '交付里程碑收益高'],
    preferred: ['sla', 'delivery'],
    resistance: { scope: 4, anger: 1 },
    phaseLines: [
      '迁移姐说“不停机最好”，博哥问“最好”写进哪张合同。',
      '友商旧配置一打开，会议室开始有点缺氧。',
    ],
    unlock: (state) =>
      state.completed.filter((id) => id !== 'boss').length >= 3 ||
      state.cycle >= 2,
    advanced: true,
  },
  {
    id: 'live',
    title: '直播峰值今晚就来',
    client: '把峰值当惊喜的直播老板',
    mapId: 'office',
    npcId: 'npc-live',
    route: 'delivery',
    recommendedLevel: 2,
    cost: 1,
    reward: 320,
    xp: 64,
    intro:
      '直播老板姐说今晚带货，流量不确定但千万别崩。博哥：不确定可以，弹性和保障不能免费。',
    winLine: '峰值预案、压测和降级开关都落表，今晚终于不是赌命。',
    partialLine: '先保核心链路，边缘功能别在今晚作妖。',
    failLine: '直播峰值把售后打成了实时弹幕，博哥被艾特到发热。',
    issue: { label: '峰值告警', type: 'pressure', severity: 11 },
    enemy: { anger: 45, budget: 50, scope: 70, trust: 24 },
    chapter: 2,
    tier: 'mid',
    riskProfile: 'mixed',
    teachingHint:
      '直播峰值先做降级和压测，不然压力会把当天经营拖爆。',
    recommendedPlan: ['fallback', 'poc', 'milestone', 'review'],
    arc: '第二幕：客户开始拿峰值许愿',
    objective: '把“不确定流量”拆成压测、弹性、降级和保障套餐。',
    traits: ['压力增长快', '交付演示有效', 'SLA 边界能保命'],
    preferred: ['delivery', 'sla'],
    resistance: { anger: 1, scope: 2 },
    phaseLines: [
      '老板姐说“今晚应该不会爆”，博哥觉得这句话本身就很爆。',
      '客户想顺手把大屏、告警、客服联动都开了。',
    ],
    unlock: (state) =>
      state.day >= 3 || state.completed.includes('sla') || state.cycle >= 2,
    advanced: true,
  },
  {
    id: 'security',
    title: '渗透测试今天要过',
    client: '手握红字报告的安全审计',
    mapId: 'clientSite',
    npcId: 'npc-security',
    route: 'boundary',
    recommendedLevel: 4,
    cost: 1,
    reward: 410,
    xp: 78,
    intro:
      '安全姐把红字报告拍桌上，说今天不过就不上线。博哥看完报告：能修，但这不是默认售后。',
    winLine: '红字被拆成修复、复测、例外说明，安全会终于不再无限加页。',
    partialLine: '高危先清，低危进例外说明，别今天全都往售后锅里塞。',
    failLine: '红字没过，客户把上线延期也算成博哥欠的。',
    issue: { label: '安全红字', type: 'compliance', severity: 14 },
    enemy: { anger: 56, budget: 45, scope: 78, trust: 22 },
    chapter: 3,
    tier: 'late',
    riskProfile: 'anger',
    teachingHint:
      '安全红字会同时涨怒气和蔓延；先降追责，再把修复拆成例外说明。',
    recommendedPlan: ['fallback', 'freeze', 'contract', 'review'],
    arc: '第三幕：验收前的红字追杀',
    objective: '把渗透测试拆成修复、复测和例外边界。',
    traits: ['合规压力强', '边界先行关键', '失败会喂 Boss'],
    preferred: ['sla', 'recovery'],
    resistance: { scope: 5, trust: 1 },
    phaseLines: [
      '安全姐说“就几个红字”，博哥数了一下，几个等于二十七个。',
      '客户想把所有修复都算进原售后，边界条开始报警。',
    ],
    unlock: (state) =>
      state.chapter >= 3 ||
      state.issues.some((issue) => issue.type === 'compliance') ||
      state.cycle >= 2,
    advanced: true,
  },
  {
    id: 'invoice',
    title: '发票合同抬头全错',
    client: '拿着三版合同的财务结算',
    mapId: 'clientSite',
    npcId: 'npc-invoice',
    route: 'business',
    recommendedLevel: 3,
    cost: 1,
    reward: 350,
    xp: 68,
    intro:
      '财务姐说抬头错、合同错、价格也错。博哥看着三版附件：这不是售后，这是考古。',
    winLine: '合同、报价、发票被对齐，钱终于能从流程里爬出来。',
    partialLine: '先把抬头和报价对上，历史附件明天继续挖。',
    failLine: '合同没对齐，回款像卡在云防火墙里。',
    issue: { label: '回款卡点', type: 'budget', severity: 12 },
    enemy: { anger: 40, budget: 34, scope: 58, trust: 30 },
    chapter: 2,
    tier: 'mid',
    riskProfile: 'budget',
    teachingHint:
      '发票合同先救现金流，预算条低的时候别把耐心耗在演示上。',
    recommendedPlan: ['anchor', 'report', 'review', 'contract'],
    arc: '第二幕：钱在流程里迷路',
    objective: '把合同、报价和发票对齐，别让售后替流程背锅。',
    traits: ['预算条很低', '商业预收强', '复盘能减少压力'],
    preferred: ['pricing', 'recovery'],
    resistance: { budget: 4 },
    phaseLines: [
      '财务姐打开第三版合同，博哥感觉自己进了版本迷宫。',
      '客户问能不能先开票再补合同，博哥听完开始找边界。',
    ],
    unlock: (state) =>
      state.stats.cash < 520 ||
      state.completed.includes('cost') ||
      state.cycle >= 2,
    advanced: true,
  },
  {
    id: 'datapack',
    title: '知识库十万条全导入',
    client: '想一口吃完数据的数据团队',
    mapId: 'clientSite',
    npcId: 'npc-datapack',
    route: 'shadow',
    recommendedLevel: 4,
    cost: 1,
    reward: 430,
    xp: 82,
    intro:
      '数据姐说十万条知识库今晚全导入，最好自动清洗、自动标注、自动上线。博哥：自动可以，奇迹不免费。',
    winLine: '数据被拆成清洗、标注、灰度和回滚，十万条终于不是一口闷。',
    partialLine: '先导高频知识，长尾数据留给影流第二案。',
    failLine: '知识库灌进去像开盲盒，AI 回答开始臭氧层子。',
    issue: { label: '知识库污染', type: 'delivery', severity: 13 },
    enemy: { anger: 44, budget: 52, scope: 82, trust: 18 },
    chapter: 3,
    tier: 'late',
    riskProfile: 'scope',
    teachingHint:
      '十万条知识库不能一口吞；影流可以分案，但必须配边界。',
    recommendedPlan: ['shadow', 'freeze', 'poc', 'milestone'],
    arc: '第三幕：AI 数据开始反噬',
    objective: '把全量导入拆成清洗、标注、灰度和回滚。',
    traits: ['范围爆炸', '影流替代方案有效', '交付信任缺口大'],
    preferred: ['shadow', 'delivery'],
    resistance: { scope: 5, trust: 2 },
    phaseLines: [
      '数据姐说全量导入省事，博哥想说省的是谁的事。',
      '客户开始问能不能顺手接图片、语音、历史工单。',
    ],
    unlock: (state) =>
      state.completed.includes('voicebot') ||
      state.routes.shadow >= 35 ||
      state.cycle >= 2,
    advanced: true,
  },
  {
    id: 'vip',
    title: 'VIP 专属通道无限保障',
    client: '坐在老板席的大客户',
    mapId: 'clientSite',
    npcId: 'npc-vip',
    route: 'shadow',
    recommendedLevel: 5,
    cost: 2,
    reward: 560,
    xp: 98,
    intro:
      'VIP 姐说专属通道要无限保障，还要半夜有人回。博哥寻思，无限这个词，听着就贵。',
    winLine: '无限保障被拆成等级、窗口、响应和加急费，VIP 终于贵得合理。',
    partialLine: '先签专属响应，半夜值守得下个单子再聊。',
    failLine: '无限保障没收住，客户把博哥当云上 24 小时人肉网关。',
    issue: { label: 'VIP 无限责任', type: 'pressure', severity: 16 },
    enemy: { anger: 60, budget: 50, scope: 86, trust: 24 },
    chapter: 3,
    tier: 'late',
    riskProfile: 'mixed',
    teachingHint:
      'VIP 是后期压力测试：行动消耗高，先准备或训练再打会明显更稳。',
    recommendedPlan: ['shadow', 'fallback', 'ladder', 'freeze'],
    arc: '第三幕：无限保障开庭',
    objective: '把无限保障拆成等级、窗口、响应和加急费。',
    traits: ['高压高奖', '消耗 2 行动', '路线构筑不足会翻车'],
    preferred: ['shadow', 'sla', 'pricing'],
    resistance: { anger: 3, scope: 6 },
    phaseLines: [
      'VIP 姐说半夜也要有人回，博哥看了眼手机电量。',
      '客户把“专属”说成“无限”，会议室瞬间变贵。',
    ],
    unlock: (state) =>
      state.chapter >= 3 &&
      (state.routes.shadow >= 30 ||
        state.routes.business >= 45 ||
        state.cycle >= 2),
    advanced: true,
  },
  {
    id: 'boss',
    title: '云上客户联合验收会',
    client: '全员在线的验收组',
    mapId: 'clientSite',
    npcId: 'npc-boss',
    route: 'shadow',
    recommendedLevel: 4,
    cost: 2,
    reward: 620,
    xp: 110,
    intro:
      '所有“再补一次”“顺手一下”“这咋收钱”汇总成联合验收姐团。博哥站到正中间，准备拉表关单。',
    winLine: '你把前面所有坑串成路线图，联合验收会终于盖章。',
    partialLine: '验收通过试运行，但下周还有一轮复盘，人这辈子。',
    failLine: '验收组把所有遗留问题合并成一个大锅，真闹心。',
    issue: { label: '联合追责', type: 'pressure', severity: 16 },
    enemy: { anger: 58, budget: 48, scope: 80, trust: 22 },
    chapter: 3,
    tier: 'boss',
    riskProfile: 'mixed',
    teachingHint:
      'Boss 三段质询：先问钱，再问交付，最后翻 SLA 和遗留。材料越多越好打。',
    recommendedPlan: ['review', 'fallback', 'mirror', 'freeze', 'demo', 'ladder'],
    arc: '第三幕：三表合一关单',
    objective: '把报价表、验收表、SLA 表摊开，处理本周所有遗留追责。',
    traits: [
      '会引用历史遗留',
      '路线最高项决定终局质询',
      '失败不会死档但下周更难',
    ],
    preferred: ['recovery', 'shadow', 'sla'],
    resistance: { anger: 3, scope: 4, trust: -2 },
    phaseLines: [
      '联合验收组翻到第一页：这单咋收钱，今天必须说清楚。',
      '前面每个“顺手一下”都坐上了会议桌。',
    ],
    unlock: (state) =>
      state.completed.filter((id) => id !== 'boss').length >= 4,
    boss: true,
    advanced: true,
  },
];

export const SKILLS: SkillDefinition[] = [
  {
    id: 'anchor',
    name: '这单咋收钱',
    category: 'business',
    training: 'pricing',
    unlockLevel: 1,
    cooldown: 1,
    energy: 8,
    patience: 4,
    line: '不是，顺手也得有价格。先把报价锚住。',
    effect: { budget: 18, anger: 4 },
    self: { cash: 12 },
  },
  {
    id: 'report',
    name: '再梳一遍账单',
    category: 'business',
    training: 'pricing',
    unlockLevel: 1,
    cooldown: 1,
    energy: 9,
    patience: 5,
    line: '我再给你梳一遍云账单，但这叫成本治理。',
    effect: { trust: 14, budget: 10, anger: -6 },
  },
  {
    id: 'ladder',
    name: '报价阶梯',
    category: 'business',
    training: 'pricing',
    unlockLevel: 3,
    cooldown: 2,
    energy: 12,
    patience: 8,
    line: '基础、专业、旗舰三档摆上桌，顺手也有顺手的价格。',
    effect: { budget: 24, trust: 8, scope: -6, anger: 5 },
    self: { cash: 28 },
  },
  {
    id: 'poc',
    name: '先做 POC',
    category: 'delivery',
    training: 'delivery',
    unlockLevel: 1,
    cooldown: 1,
    energy: 7,
    patience: 7,
    line: '先小范围跑通，别一上来把全公司押上。',
    effect: { trust: 18, scope: -10 },
  },
  {
    id: 'milestone',
    name: '验收清单',
    category: 'delivery',
    training: 'delivery',
    unlockLevel: 2,
    cooldown: 1,
    energy: 10,
    patience: 7,
    line: '把抽象满意拆成可验收的清单。',
    effect: { trust: 16, scope: -16 },
  },
  {
    id: 'demo',
    name: '场景演示',
    category: 'delivery',
    training: 'delivery',
    unlockLevel: 3,
    cooldown: 2,
    energy: 12,
    patience: 10,
    line: '别讲大词，直接跑一遍客户真实场景。',
    effect: { trust: 26, scope: -8, budget: 6 },
  },
  {
    id: 'contract',
    name: '拉表关单',
    category: 'boundary',
    training: 'sla',
    unlockLevel: 1,
    cooldown: 2,
    energy: 6,
    patience: 10,
    boundary: 5,
    line: '再不行就拉表关单吧，不能免费续杯。',
    effect: { scope: -20, anger: -8, trust: 6 },
  },
  {
    id: 'fallback',
    name: '降级预案',
    category: 'boundary',
    training: 'sla',
    unlockLevel: 2,
    cooldown: 1,
    energy: 8,
    patience: 8,
    boundary: 3,
    line: '不可控不是不管，是得写进预案。',
    effect: { anger: -14, trust: 10, scope: -8 },
  },
  {
    id: 'freeze',
    name: '风险冻结',
    category: 'boundary',
    training: 'sla',
    unlockLevel: 3,
    cooldown: 2,
    energy: 11,
    patience: 9,
    boundary: 6,
    line: '先冻结范围。不是不干，是别一边救火一边加柴。',
    effect: { scope: -26, anger: -4, trust: 4 },
  },
  {
    id: 'review',
    name: '关门复盘',
    category: 'delivery',
    training: 'recovery',
    unlockLevel: 2,
    cooldown: 2,
    energy: 4,
    patience: 5,
    line: '这锅先不背，复盘先写，别急头白脸。',
    effect: { anger: -8, trust: 8 },
    self: { energy: 8, patience: 10, pressure: -6 },
  },
  {
    id: 'shadow',
    name: '影流三方案',
    category: 'shadow',
    training: 'shadow',
    unlockLevel: 3,
    cooldown: 2,
    energy: 12,
    patience: 8,
    line: 'A 稳，B 快，C 看起来非常旗舰。',
    effect: { trust: 20, budget: 10, scope: -14, anger: 6 },
  },
  {
    id: 'split',
    name: '分身会审',
    category: 'shadow',
    training: 'shadow',
    unlockLevel: 4,
    cooldown: 3,
    energy: 16,
    patience: 10,
    line: 'ShadowBo 入场，三个角度同时救火。',
    effect: { trust: 28, anger: -12, scope: -10 },
    self: { pressure: -10 },
  },
  {
    id: 'mirror',
    name: '影流报价镜',
    category: 'shadow',
    training: 'shadow',
    unlockLevel: 5,
    cooldown: 3,
    energy: 18,
    patience: 12,
    line: '三套方案三套价，客户挑来挑去，发现每条都得付钱。',
    effect: { budget: 30, trust: 16, scope: -18, anger: 8 },
    self: { cash: 45, pressure: -8 },
  },
];

export const ACHIEVEMENTS: AchievementDefinition[] = [
  {
    id: 'first-paid-ledger',
    title: '第一张收费表',
    description: '赢下 GPU 账单，把免费售后写进报价。',
    route: 'business',
  },
  {
    id: 'first-bad-debt',
    title: '第一次售后债',
    description: '谈判失败后留下一个遗留问题。',
  },
  {
    id: 'first-gray-acceptance',
    title: '灰度通过',
    description: '拿到一次部分成功，客户没走但锅还在。',
    route: 'delivery',
  },
  {
    id: 'boss-ready',
    title: '联合验收入场券',
    description: '完成 4 个普通客户，Boss 议程打开。',
  },
  {
    id: 'build-online',
    title: '博哥构筑成型',
    description: '拥有 3 个训练特质。',
  },
  {
    id: 'clean-docket',
    title: '干净案卷',
    description: '没有遗留问题时推进到 Boss。',
    route: 'boundary',
  },
  {
    id: 'comeback-week',
    title: '这锅我又捡回来了',
    description: '失败后重试同一客户并成功。',
  },
  {
    id: 'shadow-online',
    title: '影流上线',
    description: '解锁影流分身特质。',
    route: 'shadow',
  },
  {
    id: 'ending-business',
    title: '商业封神线',
    description: '用报价路线通过联合验收。',
    route: 'business',
  },
  {
    id: 'ending-delivery',
    title: '交付稳态线',
    description: '用交付路线通过联合验收。',
    route: 'delivery',
  },
  {
    id: 'ending-boundary',
    title: 'SLA 宗师线',
    description: '用边界路线通过联合验收。',
    route: 'boundary',
  },
  {
    id: 'ending-shadow',
    title: '影流整活隐藏线',
    description: '用影流路线通过联合验收。',
    route: 'shadow',
  },
];

export const STORY_CARDS: StoryCardDefinition[] = [
  {
    id: 'opening',
    title: '开场：这单咋收钱',
    line: '客户姐把账单、Agent、SLA 和合规材料一起拍桌上，博哥决定把免费售后改造成经营。',
    unlockHint: '进入游戏',
  },
  {
    id: 'chapter-2',
    title: '第二幕：顺手开始复用',
    line: '客户学会了“顺手一下”：私有化、日报、三方案全都想免费续杯。',
    unlockHint: '完成 2 个普通客户',
  },
  {
    id: 'chapter-3',
    title: '第三幕：联合验收开庭',
    line: '前面所有“再补一次”合并成 Boss 议程，博哥必须三表合一。',
    unlockHint: '完成 4 个普通客户，Boss 议程打开',
  },
  {
    id: 'first-bad-debt',
    title: '售后债',
    line: '失败不会死档，但客户会冷却、截图会回流、Boss 会点名。',
    unlockHint: '失败一次',
  },
  {
    id: 'build-online',
    title: '构筑成型',
    line: '训练不再只是 +1，报价、交付、SLA、复盘、影流都能改变打法。',
    unlockHint: '拥有 3 个特质',
  },
  {
    id: 'route:business-45',
    title: '路线：套餐意识',
    line: '免费、基础、旗舰三档摆上桌，客户第一次意识到“顺手”也有价格。',
    unlockHint: '商业路线达到 45',
    route: 'business',
  },
  {
    id: 'route:business-70',
    title: '路线：收款节点',
    line: '博哥把每个解释动作挂到付款节点上，售后开始像经营，不像陪聊。',
    unlockHint: '商业路线达到 70',
    route: 'business',
  },
  {
    id: 'route:delivery-45',
    title: '路线：满意可签字',
    line: '“满意”被拆成清单，客户不能再把情绪当验收标准。',
    unlockHint: '交付路线达到 45',
    route: 'delivery',
  },
  {
    id: 'route:delivery-70',
    title: '路线：试运行剧本',
    line: '试运行有了剧本，老板姐临场加戏也要先进变更单。',
    unlockHint: '交付路线达到 70',
    route: 'delivery',
  },
  {
    id: 'route:boundary-45',
    title: '路线：变更单护体',
    line: '顺手项不再靠嘴挡，变更单开始替博哥说话。',
    unlockHint: '边界路线达到 45',
    route: 'boundary',
  },
  {
    id: 'route:boundary-70',
    title: '路线：红线清单',
    line: '能做、不能做、加钱做，三列一落表，会议室就安静。',
    unlockHint: '边界路线达到 70',
    route: 'boundary',
  },
  {
    id: 'route:shadow-45',
    title: '路线：分身会审',
    line: 'ShadowBo 从脑内走到会议桌边，客户以为自己看见了很多选择。',
    unlockHint: '影流路线达到 45',
    route: 'shadow',
  },
  {
    id: 'route:shadow-70',
    title: '路线：选择权幻觉',
    line: '客户选来选去，发现每条都在博哥的报价表里。',
    unlockHint: '影流路线达到 70',
    route: 'shadow',
  },
  {
    id: 'long-goal:ledger-master',
    title: '长期：收费不再靠吼',
    line: '每个“再嗦一次”都能落回报价底稿，博哥终于不用靠嗓门守现金流。',
    unlockHint: '完成长期目标「收费不再靠吼」',
    route: 'business',
  },
  {
    id: 'long-goal:delivery-handbook',
    title: '长期：验收不是玄学',
    line: '客户说满意时，博哥能翻到对应验收项；客户说不满意时，也得指出是哪一项。',
    unlockHint: '完成长期目标「验收不是玄学」',
    route: 'delivery',
  },
  {
    id: 'long-goal:sla-wall',
    title: '长期：拉表关单墙',
    line: 'SLA 红线贴满办公室，不是不管，是锅不能自己长腿跑到博哥背上。',
    unlockHint: '完成长期目标「拉表关单墙」',
    route: 'boundary',
  },
  {
    id: 'long-goal:shadow-director',
    title: '长期：影流导演',
    line: 'A/B/C 三案不再是花活，而是让客户在可收费的范围里做选择。',
    unlockHint: '完成长期目标「影流导演」',
    route: 'shadow',
  },
  {
    id: 'long-goal:case-archive-collector',
    title: '长期：案卷收藏家',
    line: '失败、灰度、胜利都进案卷柜；过去的锅，今天也能当证据。',
    unlockHint: '完成长期目标「案卷收藏家」',
    route: 'boundary',
  },
  {
    id: 'long-goal:legacy-quartet',
    title: '长期：四线遗产',
    line: '四条路线都留下传家宝，下周目开局终于不像裸奔接客诉。',
    unlockHint: '完成长期目标「四线遗产」',
    route: 'shadow',
  },
  {
    id: 'ending-business',
    title: '结局：商业封神线',
    line: '博哥把所有顺手项折成报价阶梯。免费可以聊，交付得收钱。',
    unlockHint: '商业线通关',
    route: 'business',
  },
  {
    id: 'ending-delivery',
    title: '结局：交付稳态线',
    line: '博哥把“满意”拆成验收清单。写不出来就别急头白脸。',
    unlockHint: '交付线通关',
    route: 'delivery',
  },
  {
    id: 'ending-boundary',
    title: '结局：SLA 宗师线',
    line: '博哥把 SLA、补材料、二开全写进表。不是不管，是别让我免费背锅。',
    unlockHint: '边界线通关',
    route: 'boundary',
  },
  {
    id: 'ending-shadow',
    title: '结局：影流整活隐藏线',
    line: 'ShadowBo 递 A/B/C 三案，客户以为自己赢了，其实每条都有价格。',
    unlockHint: '影流线通关',
    route: 'shadow',
  },
];

export const CASE_MEMORIES: CaseMemoryDefinition[] = [
  {
    id: 'gpu-win-memory',
    questId: 'gpu',
    outcome: 'win',
    title: '案卷：账单终于能收钱',
    line: '博哥把 GPU 账单拆成训练、推理、空转三列。财务姐没完全开心，但终于知道钱不是凭空没的。',
    unlockHint: '赢下 GPU 账单',
    route: 'business',
  },
  {
    id: 'gpu-partial-memory',
    questId: 'gpu',
    outcome: 'partial',
    title: '案卷：梳过但没梳透',
    line: '账单讲了一半，客户先点头后截图。博哥明白了，售后最怕“差不多懂了”。',
    unlockHint: 'GPU 账单部分成功',
    route: 'delivery',
  },
  {
    id: 'gpu-fail-memory',
    questId: 'gpu',
    outcome: 'fail',
    title: '旧账：截图进群',
    line: '财务姐那张截图变成群公告。博哥记下第一条铁律：解释不收费，截图会复利。',
    unlockHint: 'GPU 账单失败',
  },
  {
    id: 'agent-win-memory',
    questId: 'agent',
    outcome: 'win',
    title: '案卷：今天上线但不全量',
    line: 'Agent 被拆成 POC、灰度、验收三段。老板姐说“也行”，博哥听见的是“终于能报价”。',
    unlockHint: '赢下 Agent 上线',
    route: 'delivery',
  },
  {
    id: 'agent-partial-memory',
    questId: 'agent',
    outcome: 'partial',
    title: '案卷：POC 和全量之间',
    line: '客户答应先 POC，但嘴上还挂着 CRM、客服、日报。需求没有消失，只是换了个会议室。',
    unlockHint: 'Agent 部分成功',
    route: 'delivery',
  },
  {
    id: 'agent-fail-memory',
    questId: 'agent',
    outcome: 'fail',
    title: '旧账：顺手变默认',
    line: '“今天上线”把所有系统都吸了进来。博哥第一次觉得“顺手”这俩字有攻击性。',
    unlockHint: 'Agent 失败',
  },
  {
    id: 'sla-win-memory',
    questId: 'sla',
    outcome: 'win',
    title: '案卷：两秒归两秒',
    line: 'SLA 表贴出来后，群聊从开庭变排期。博哥发现边界不是冷漠，是保命。',
    unlockHint: '赢下 SLA 追责',
    route: 'boundary',
  },
  {
    id: 'sla-partial-memory',
    questId: 'sla',
    outcome: 'partial',
    title: '案卷：半张 SLA 表',
    line: '客户暂时接受说明，但“两秒”还在群里回响。半张表能止血，不能结案。',
    unlockHint: 'SLA 部分成功',
    route: 'boundary',
  },
  {
    id: 'sla-fail-memory',
    questId: 'sla',
    outcome: 'fail',
    title: '旧账：群聊开庭',
    line: '两秒截图被置顶，博哥被艾特到没脾气。人这辈子，不能让群聊审合同。',
    unlockHint: 'SLA 失败',
  },
  {
    id: 'private-win-memory',
    questId: 'private',
    outcome: 'win',
    title: '案卷：合规也有套餐',
    line: '离线、审计、脱敏被拆成三包，合规姐终于不把材料当默认赠品。',
    unlockHint: '赢下私有化合规',
    route: 'boundary',
  },
  {
    id: 'private-partial-memory',
    questId: 'private',
    outcome: 'partial',
    title: '案卷：材料先别下崽',
    line: '基础材料先落地，审计夜袭留到复盘。博哥知道这不是结束，是把锅切小。',
    unlockHint: '私有化合规部分成功',
    route: 'boundary',
  },
  {
    id: 'private-fail-memory',
    questId: 'private',
    outcome: 'fail',
    title: '旧账：文档繁殖',
    line: '文档从一份变三份，还都要明早。博哥怀疑合规材料会自己繁殖。',
    unlockHint: '私有化合规失败',
  },
  {
    id: 'cost-win-memory',
    questId: 'cost',
    outcome: 'win',
    title: '案卷：日报不是免费大屏',
    line: '日报、阈值、预警被摆成套餐，运营姐终于承认“换个展示”也有人力成本。',
    unlockHint: '赢下成本治理',
    route: 'business',
  },
  {
    id: 'cost-partial-memory',
    questId: 'cost',
    outcome: 'partial',
    title: '案卷：先收半口气',
    line: '客户先买基础日报，阈值和大屏还在旁边眨眼。钱到账一点，锅也少一点。',
    unlockHint: '成本治理部分成功',
    route: 'business',
  },
  {
    id: 'cost-fail-memory',
    questId: 'cost',
    outcome: 'fail',
    title: '旧账：免费续杯',
    line: '免费大屏开了口，售后像饮料机一样被续杯。博哥记住：默认值最贵。',
    unlockHint: '成本治理失败',
  },
  {
    id: 'shadow-win-memory',
    questId: 'shadow',
    outcome: 'win',
    title: '案卷：三案都有价格',
    line: 'A 稳、B 快、C 旗舰，客户获得选择权，博哥保住收费权。ShadowBo 在门口点头。',
    unlockHint: '赢下影流三方案',
    route: 'shadow',
  },
  {
    id: 'shadow-partial-memory',
    questId: 'shadow',
    outcome: 'partial',
    title: '案卷：B 方案先走',
    line: '客户选了 B，心里还惦记 A 和 C。影流不是魔法，是让客户把幻想排队。',
    unlockHint: '影流方案部分成功',
    route: 'shadow',
  },
  {
    id: 'shadow-fail-memory',
    questId: 'shadow',
    outcome: 'fail',
    title: '旧账：第四方案',
    line: '三案没收住，客户问 D。ShadowBo 沉默，博哥知道自己影流过拟合了。',
    unlockHint: '影流方案失败',
  },
  {
    id: 'voicebot-win-memory',
    questId: 'voicebot',
    outcome: 'win',
    title: '案卷：AI 客服戴上护栏',
    line: '夜间话术终于有了护栏，机器人没变聪明，但至少不再自信地送赠品。',
    unlockHint: '赢下 AI 客服夜里胡说',
    route: 'delivery',
  },
  {
    id: 'voicebot-partial-memory',
    questId: 'voicebot',
    outcome: 'partial',
    title: '案卷：高危词先挡',
    line: '高危词被挡住，知识库还在漏风。博哥把“以后再补”写成下一阶段。',
    unlockHint: 'AI 客服部分成功',
    route: 'delivery',
  },
  {
    id: 'voicebot-fail-memory',
    questId: 'voicebot',
    outcome: 'fail',
    title: '旧账：机器人继续嘴硬',
    line: 'AI 客服继续胡说，客户群截图飞起。博哥意识到模型幻觉也会变成售后债。',
    unlockHint: 'AI 客服失败',
  },
  {
    id: 'quota-win-memory',
    questId: 'quota',
    outcome: 'win',
    title: '案卷：GPU 插队有价',
    line: '配额、预留、加急被拆开报价。客户终于明白算力不是空气，插队也不是感情。',
    unlockHint: '赢下 H200 配额插队',
    route: 'business',
  },
  {
    id: 'quota-partial-memory',
    questId: 'quota',
    outcome: 'partial',
    title: '案卷：一半配额先跑',
    line: '一半配额先落地，剩下靠预收款续命。博哥没全赢，但现金没死。',
    unlockHint: 'GPU 配额部分成功',
    route: 'business',
  },
  {
    id: 'quota-fail-memory',
    questId: 'quota',
    outcome: 'fail',
    title: '旧账：算力像空气',
    line: '配额没锚住，客户开始觉得云资源应该随叫随到。博哥听完想把报价表贴脸上。',
    unlockHint: 'GPU 配额失败',
  },
  {
    id: 'migration-win-memory',
    questId: 'migration',
    outcome: 'win',
    title: '案卷：迁移神话落地',
    line: '三天迁移被拆成演练、窗口、回滚，神话终于变成项目计划。',
    unlockHint: '赢下跨云迁移',
    route: 'boundary',
  },
  {
    id: 'migration-partial-memory',
    questId: 'migration',
    outcome: 'partial',
    title: '案卷：先搬非核心',
    line: '非核心先搬，核心系统等窗口。客户不爽，但至少没把生产环境当纸飞机。',
    unlockHint: '跨云迁移部分成功',
    route: 'delivery',
  },
  {
    id: 'migration-fail-memory',
    questId: 'migration',
    outcome: 'fail',
    title: '旧账：割接追责',
    line: '迁移窗口没守住，客户把停机也算售后。博哥记住：三天完成一般等于三天开庭。',
    unlockHint: '跨云迁移失败',
  },
  {
    id: 'live-win-memory',
    questId: 'live',
    outcome: 'win',
    title: '案卷：峰值不靠赌命',
    line: '压测、弹性、降级开关都上了桌，今晚终于不是拿博哥寿命当缓存。',
    unlockHint: '赢下直播峰值',
    route: 'delivery',
  },
  {
    id: 'live-partial-memory',
    questId: 'live',
    outcome: 'partial',
    title: '案卷：先保核心链路',
    line: '核心链路保住了，边缘功能先别作妖。客户嫌少，博哥嫌命短。',
    unlockHint: '直播峰值部分成功',
    route: 'boundary',
  },
  {
    id: 'live-fail-memory',
    questId: 'live',
    outcome: 'fail',
    title: '旧账：峰值弹幕',
    line: '直播峰值把售后打成实时弹幕，博哥被艾特到手机发热。',
    unlockHint: '直播峰值失败',
  },
  {
    id: 'security-win-memory',
    questId: 'security',
    outcome: 'win',
    title: '案卷：红字变清单',
    line: '渗透测试红字被拆成修复、复测、例外说明，安全会终于不是无限加页。',
    unlockHint: '赢下渗透测试',
    route: 'boundary',
  },
  {
    id: 'security-partial-memory',
    questId: 'security',
    outcome: 'partial',
    title: '案卷：高危先清',
    line: '高危红字先清，低危进例外。今天不完美，但至少能上线呼吸。',
    unlockHint: '渗透测试部分成功',
    route: 'boundary',
  },
  {
    id: 'security-fail-memory',
    questId: 'security',
    outcome: 'fail',
    title: '旧账：红字过夜',
    line: '红字没过，客户把延期也记到售后头上。博哥看见安全报告就开始心虚。',
    unlockHint: '渗透测试失败',
  },
  {
    id: 'invoice-win-memory',
    questId: 'invoice',
    outcome: 'win',
    title: '案卷：钱从流程里爬出',
    line: '合同、报价、发票终于对齐。钱到账那一刻，博哥觉得表格也有生命。',
    unlockHint: '赢下发票合同',
    route: 'business',
  },
  {
    id: 'invoice-partial-memory',
    questId: 'invoice',
    outcome: 'partial',
    title: '案卷：先对齐抬头',
    line: '抬头和报价先对上，历史附件明天继续挖。至少钱不再完全迷路。',
    unlockHint: '发票合同部分成功',
    route: 'business',
  },
  {
    id: 'invoice-fail-memory',
    questId: 'invoice',
    outcome: 'fail',
    title: '旧账：回款卡点',
    line: '回款像卡在云防火墙里。博哥明白合同不是行政活，是现金流 Boss。',
    unlockHint: '发票合同失败',
  },
  {
    id: 'datapack-win-memory',
    questId: 'datapack',
    outcome: 'win',
    title: '案卷：十万条不一口闷',
    line: '清洗、标注、灰度、回滚分开落地，知识库终于不像开盲盒。',
    unlockHint: '赢下知识库导入',
    route: 'shadow',
  },
  {
    id: 'datapack-partial-memory',
    questId: 'datapack',
    outcome: 'partial',
    title: '案卷：先导高频知识',
    line: '高频知识先上线，长尾数据留给第二案。影流不是炫，是给风险排队。',
    unlockHint: '知识库部分成功',
    route: 'shadow',
  },
  {
    id: 'datapack-fail-memory',
    questId: 'datapack',
    outcome: 'fail',
    title: '旧账：知识库污染',
    line: '十万条一口闷灌进去，AI 回答开始抽象。博哥闻到了数据债的味儿。',
    unlockHint: '知识库失败',
  },
  {
    id: 'vip-win-memory',
    questId: 'vip',
    outcome: 'win',
    title: '案卷：无限保障有价格',
    line: '专属通道被拆成等级、窗口、响应和加急费。VIP 仍然贵，但贵得合理。',
    unlockHint: '赢下 VIP 专属通道',
    route: 'shadow',
  },
  {
    id: 'vip-partial-memory',
    questId: 'vip',
    outcome: 'partial',
    title: '案卷：先签专属响应',
    line: '专属响应先签，半夜值守另算。博哥没把无限责任全接回家。',
    unlockHint: 'VIP 部分成功',
    route: 'business',
  },
  {
    id: 'vip-fail-memory',
    questId: 'vip',
    outcome: 'fail',
    title: '旧账：人肉网关',
    line: '无限保障没收住，客户把博哥当 24 小时人肉网关。影流也救不了没边界的爱。',
    unlockHint: 'VIP 失败',
  },
  {
    id: 'boss-win-memory',
    questId: 'boss',
    outcome: 'win',
    title: '终局：验收盖章',
    line: '报价表、验收表、SLA 表终于合成一张路线图。博哥不是把姐说服了，是把姐的每个“顺手”都写进价格。',
    unlockHint: '赢下联合验收',
  },
  {
    id: 'boss-partial-memory',
    questId: 'boss',
    outcome: 'partial',
    title: '终局：试运行不是胜利',
    line: '验收组给了试运行，没给盖章。博哥带着半张胜利回办公室，明天继续拉表。',
    unlockHint: '联合验收部分成功',
  },
  {
    id: 'boss-fail-memory',
    questId: 'boss',
    outcome: 'fail',
    title: '终局旧账：大锅合并',
    line: '所有遗留合并成一个大锅，会议室空气按分钟收费。失败不是死档，是下周目开局压力。',
    unlockHint: '联合验收失败',
  },
];

export const ROUTE_MILESTONES: RouteMilestoneDefinition[] = [
  {
    id: 'business-20',
    route: 'business',
    threshold: 20,
    title: '报价线 20：先问钱怎么收',
    line: '博哥开始条件反射：这事先别玄学，先问钱怎么收。',
    rewardLine: '路线奖励：现金 +90，商业技能更容易稳预算。',
    effect: { cash: 90 },
  },
  {
    id: 'business-45',
    route: 'business',
    threshold: 45,
    title: '报价线 45：套餐意识',
    line: '免费、基础、旗舰三档摆出来，客户突然不太会说“顺手”了。',
    rewardLine: '路线奖励：现金 +150，口碑 +3。',
    effect: { cash: 150, reputation: 3 },
  },
  {
    id: 'business-70',
    route: 'business',
    threshold: 70,
    title: '报价线 70：收款节点',
    line: '博哥把每个解释动作都挂到节点上，售后开始像经营，不像陪聊。',
    rewardLine: '路线奖励：现金 +220，压力 -6。',
    effect: { cash: 220, pressure: -6 },
  },
  {
    id: 'business-95',
    route: 'business',
    threshold: 95,
    title: '报价线 95：姐别白嗦',
    line: '客户还没开口，报价台账已经自己翻到对应套餐。',
    rewardLine: '路线奖励：现金 +320，边界 +4。',
    effect: { cash: 320, boundary: 4 },
  },
  {
    id: 'delivery-20',
    route: 'delivery',
    threshold: 20,
    title: '交付线 20：先验后吹',
    line: '博哥不再讲大词，先把 POC、灰度、验收摆明白。',
    rewardLine: '路线奖励：口碑 +5，耐心 +5。',
    effect: { reputation: 5, patience: 5 },
  },
  {
    id: 'delivery-45',
    route: 'delivery',
    threshold: 45,
    title: '交付线 45：满意可签字',
    line: '“满意”被拆成清单，客户没法拿情绪当验收标准。',
    rewardLine: '路线奖励：口碑 +8，体力 +6。',
    effect: { reputation: 8, energy: 6 },
  },
  {
    id: 'delivery-70',
    route: 'delivery',
    threshold: 70,
    title: '交付线 70：试运行剧本',
    line: '每次试运行都有剧本，老板姐想临场加戏也得先进变更单。',
    rewardLine: '路线奖励：口碑 +10，压力 -8。',
    effect: { reputation: 10, pressure: -8 },
  },
  {
    id: 'delivery-95',
    route: 'delivery',
    threshold: 95,
    title: '交付线 95：验收稳态',
    line: '博哥把客户的“差不多”训练成了“可以签”。',
    rewardLine: '路线奖励：口碑 +14，耐心 +8。',
    effect: { reputation: 14, patience: 8 },
  },
  {
    id: 'boundary-20',
    route: 'boundary',
    threshold: 20,
    title: '边界线 20：先贴 SLA',
    line: '群聊刚要开庭，博哥已经把 SLA 表贴了出去。',
    rewardLine: '路线奖励：边界 +6，压力 -4。',
    effect: { boundary: 6, pressure: -4 },
  },
  {
    id: 'boundary-45',
    route: 'boundary',
    threshold: 45,
    title: '边界线 45：变更单护体',
    line: '顺手项不再靠嘴挡，变更单开始替博哥说话。',
    rewardLine: '路线奖励：边界 +8，耐心 +4。',
    effect: { boundary: 8, patience: 4 },
  },
  {
    id: 'boundary-70',
    route: 'boundary',
    threshold: 70,
    title: '边界线 70：红线清单',
    line: '能做、不能做、加钱做，三列一落表，会议室就安静。',
    rewardLine: '路线奖励：边界 +10，压力 -10。',
    effect: { boundary: 10, pressure: -10 },
  },
  {
    id: 'boundary-95',
    route: 'boundary',
    threshold: 95,
    title: '边界线 95：拉表关单',
    line: '博哥终于不用解释“不行”，表格会替他说。',
    rewardLine: '路线奖励：边界 +14，口碑 +4。',
    effect: { boundary: 14, reputation: 4 },
  },
  {
    id: 'shadow-20',
    route: 'shadow',
    threshold: 20,
    title: '影流线 20：三案成形',
    line: 'A 稳、B 快、C 旗舰第一次不只是整活，而是收费结构。',
    rewardLine: '路线奖励：耐心 +6，压力 -3。',
    effect: { patience: 6, pressure: -3 },
  },
  {
    id: 'shadow-45',
    route: 'shadow',
    threshold: 45,
    title: '影流线 45：分身会审',
    line: 'ShadowBo 开始从脑内走到会议桌边，客户以为自己看见了很多选择。',
    rewardLine: '路线奖励：耐心 +8，现金 +80。',
    effect: { patience: 8, cash: 80 },
  },
  {
    id: 'shadow-70',
    route: 'shadow',
    threshold: 70,
    title: '影流线 70：选择权幻觉',
    line: '客户选来选去，发现每条都在博哥的报价表里。',
    rewardLine: '路线奖励：现金 +160，压力 -8。',
    effect: { cash: 160, pressure: -8 },
  },
  {
    id: 'shadow-95',
    route: 'shadow',
    threshold: 95,
    title: '影流线 95：关灯后三案',
    line: 'ShadowBo 在会议结束后还留了一张备用表，专治第四方案。',
    rewardLine: '路线奖励：耐心 +12，边界 +6。',
    effect: { patience: 12, boundary: 6 },
  },
];

export const LEGACIES: LegacyDefinition[] = [
  {
    id: 'legacy-business',
    route: 'business',
    title: '周目遗产：报价底稿',
    line: '上周目留下报价底稿，新客户一进门就知道免费不是默认项。',
    effectLine: '商业技能预算收益 +3，通关后开局现金 +160。',
    effect: { cash: 160 },
  },
  {
    id: 'legacy-delivery',
    route: 'delivery',
    title: '周目遗产：验收模板',
    line: '上周目的验收模板被贴在会议室，老板姐临时加戏也得先填表。',
    effectLine: '交付技能信任收益 +3，通关后口碑 +6。',
    effect: { reputation: 6 },
  },
  {
    id: 'legacy-boundary',
    route: 'boundary',
    title: '周目遗产：SLA 红线',
    line: 'SLA 红线变成办公室墙上的常驻贴纸，顺手项撞上去会疼。',
    effectLine: '失败遗留严重度 -2，通关后边界 +8。',
    effect: { boundary: 8 },
  },
  {
    id: 'legacy-shadow',
    route: 'shadow',
    title: '周目遗产：影流脚本',
    line: 'ShadowBo 留下三套脚本，下周目技能槽更早打开，第四方案没那么吓人。',
    effectLine: '技能槽 +1，通关后耐心 +8。',
    effect: { patience: 8 },
  },
];

export const WEEKLY_GOALS: WeeklyGoalDefinition[] = [
  {
    id: 'cash-week',
    title: '本周收款不能虚',
    description: '现金达到 ¥900，证明售后不是公益摊。',
    target: 900,
    route: 'business',
    rewardLine: '周目标奖励：报价训练灵感、现金 +120。',
  },
  {
    id: 'trust-week',
    title: '别只会收钱',
    description: '累计客户关系达到 45，让客户觉得不是被割，是被安排。',
    target: 45,
    route: 'delivery',
    rewardLine: '周目标奖励：交付路线 +8，口碑 +6。',
  },
  {
    id: 'clean-week',
    title: '别把锅带进 Boss',
    description: '遗留问题不超过 1 个时推进到第三幕。',
    target: 1,
    route: 'boundary',
    rewardLine: '周目标奖励：边界 +8，压力 -10。',
  },
  {
    id: 'shadow-week',
    title: '影流不能只帅',
    description: '影流路线达到 35，并至少完成一个现场客户。',
    target: 35,
    route: 'shadow',
    rewardLine: '周目标奖励：影流路线 +10，耐心 +8。',
  },
  {
    id: 'comeback-week-goal',
    title: '失败客户也要捞回来',
    description: '本周至少重试成功一次失败客户。',
    target: 1,
    route: 'delivery',
    rewardLine: '周目标奖励：口碑 +10，压力 -8。',
  },
  {
    id: 'boss-week-goal',
    title: '联合验收不是旅游',
    description: '完成 4 个普通客户并打开 Boss 议程。',
    target: 4,
    route: 'boundary',
    rewardLine: '周目标奖励：验收预案强化，边界 +6。',
  },
];

export const LONG_TERM_GOALS: LongTermGoalDefinition[] = [
  {
    id: 'ledger-master',
    title: '长期目标：收费不再靠吼',
    description: '商业路线达到 80。每个“顺手”都能找到价格锚点。',
    target: 80,
    route: 'business',
    metric: 'route',
    rewardLine: '长期奖励：现金 +260，Boss 预算质询 -8。',
    storyLine: '博哥把免费售后折成报价阶梯，客户再说“顺手”时，表格自己翻页。',
  },
  {
    id: 'delivery-handbook',
    title: '长期目标：验收不是玄学',
    description: '交付路线达到 80。满意、试运行、上线都变成可签字动作。',
    target: 80,
    route: 'delivery',
    metric: 'route',
    rewardLine: '长期奖励：口碑 +10，Boss 信任缺口 -8。',
    storyLine: '博哥把“再嗦一次”写成验收手册，客户终于不拿情绪当标准。',
  },
  {
    id: 'sla-wall',
    title: '长期目标：拉表关单墙',
    description: '边界路线达到 80。SLA、变更单、降级预案能挡住大多数锅。',
    target: 80,
    route: 'boundary',
    metric: 'route',
    rewardLine: '长期奖励：边界 +12，Boss 怒气 -8。',
    storyLine: '办公室墙上贴满红线清单，不是不管，是别让我免费背锅。',
  },
  {
    id: 'shadow-director',
    title: '长期目标：影流导演',
    description: '影流路线达到 80。A/B/C 三案从整活变成结构化选择。',
    target: 80,
    route: 'shadow',
    metric: 'route',
    rewardLine: '长期奖励：耐心 +12，Boss 需求蔓延 -8。',
    storyLine: 'ShadowBo 不再只负责帅，三套方案都带价格、风险和退路。',
  },
  {
    id: 'ten-case-office',
    title: '长期目标：十案办公室',
    description: '累计完成 10 个普通客户。客户池开始像经营，而不是一次性剧本。',
    target: 10,
    route: 'delivery',
    metric: 'completed',
    rewardLine: '长期奖励：口碑 +8，现金 +120。',
    storyLine:
      '第十个客户结案后，博哥发现自己不是在救火，是在运营一个售后产品。',
  },
  {
    id: 'case-archive-collector',
    title: '长期目标：案卷收藏家',
    description: '解锁 18 条剧情案卷或故事卡。失败、部分成功和胜利都变成经验。',
    target: 18,
    route: 'boundary',
    metric: 'codex',
    rewardLine: '长期奖励：压力 -14，复盘收益提高。',
    storyLine: '案卷柜越来越厚，博哥终于能用过去的锅挡住今天的锅。',
  },
  {
    id: 'client-trust-network',
    title: '长期目标：客户关系网',
    description: '累计正向客户关系达到 120。让客户觉得不是被割，是被安排。',
    target: 120,
    route: 'delivery',
    metric: 'relationships',
    rewardLine: '长期奖励：口碑 +12，Boss 开局信任 +6。',
    storyLine: '客户开始互相介绍：找博哥贵一点，但至少知道贵在哪。',
  },
  {
    id: 'clean-boss-docket',
    title: '长期目标：干净验收桌',
    description: '第三幕时遗留问题为 0 并击败 Boss。不是没锅，是锅都结清了。',
    target: 1,
    route: 'boundary',
    metric: 'clean-boss',
    rewardLine: '长期奖励：周目遗产额外强化，Boss 审判少一轮旧账。',
    storyLine: '联合验收桌上没有旧账，验收组只好认真讨论价格。',
  },
  {
    id: 'legacy-quartet',
    title: '长期目标：四线遗产',
    description: '收集 4 条周目遗产。商业、交付、边界、影流都留下传家宝。',
    target: 4,
    route: 'shadow',
    metric: 'legacies',
    rewardLine: '长期奖励：技能槽更早打开，现金 +240。',
    storyLine: '四条路线都留下东西，博哥的下周目不再是裸奔开局。',
  },
  {
    id: 'cashflow-fortress',
    title: '长期目标：现金流堡垒',
    description: '现金达到 ¥1800。售后有现金垫，不怕客户把付款拖成连续剧。',
    target: 1800,
    route: 'business',
    metric: 'cash',
    rewardLine: '长期奖励：维护成本压力下降，Boss 预算质询 -6。',
    storyLine: '现金流厚起来后，博哥终于敢对客户说：可以，但这是加急包。',
  },
];

export const BOSS_DOCKET_CARDS: BossDocketCardDefinition[] = [
  {
    id: 'ledger-master',
    title: 'Boss 材料：报价底稿',
    unlockHint: '完成长期目标「收费不再靠吼」。',
    line: '博哥把所有免费项摊成三档报价，验收组预算质询少了一刀。',
    route: 'business',
    effect: { budget: 8, anger: -4 },
  },
  {
    id: 'delivery-handbook',
    title: 'Boss 材料：验收手册',
    unlockHint: '完成长期目标「验收不是玄学」。',
    line: 'POC、试运行、全量上线被拆开签字，客户没法把满意说成玄学。',
    route: 'delivery',
    effect: { trust: 8, scope: -4 },
  },
  {
    id: 'sla-wall',
    title: 'Boss 材料：SLA 红线墙',
    unlockHint: '完成长期目标「拉表关单墙」。',
    line: '两秒截图撞上 SLA 红线，验收组怒气被表格吸收了一截。',
    route: 'boundary',
    effect: { anger: -8, scope: -3 },
    self: { boundary: 4 },
  },
  {
    id: 'shadow-director',
    title: 'Boss 材料：影流分镜',
    unlockHint: '完成长期目标「影流导演」。',
    line: 'A/B/C 三案变成验收分镜，第四方案没那么容易钻出来。',
    route: 'shadow',
    effect: { scope: -8, trust: 4 },
    self: { patience: 4 },
  },
  {
    id: 'ten-case-office',
    title: 'Boss 材料：十案样本',
    unlockHint: '完成长期目标「十案办公室」。',
    line: '十个客户样本摆上桌，博哥不再是凭嘴说，而是拿案例压场。',
    route: 'delivery',
    effect: { trust: 6, anger: -3 },
  },
  {
    id: 'case-archive-collector',
    title: 'Boss 材料：案卷柜',
    unlockHint: '完成长期目标「案卷收藏家」。',
    line: '失败、灰度、胜利都写成案卷，旧锅不再只是伤疤，也是证据。',
    route: 'boundary',
    effect: { anger: -4, scope: -4 },
    self: { pressure: -6 },
  },
  {
    id: 'client-trust-network',
    title: 'Boss 材料：客户转介绍',
    unlockHint: '完成长期目标「客户关系网」。',
    line: '老客户替博哥说了两句，验收组终于承认贵有贵的理由。',
    route: 'delivery',
    effect: { trust: 10 },
  },
  {
    id: 'clean-boss-docket',
    title: 'Boss 材料：干净验收桌',
    unlockHint: '完成长期目标「干净验收桌」。',
    line: '没有旧账可以翻，验收组只能当场谈本单边界。',
    route: 'boundary',
    effect: { anger: -7, scope: -7, budget: 4 },
  },
  {
    id: 'legacy-quartet',
    title: 'Boss 材料：四线遗产',
    unlockHint: '完成长期目标「四线遗产」。',
    line: '商业、交付、边界、影流四张底牌齐亮，联合验收不再是一张嘴硬扛。',
    route: 'shadow',
    effect: { trust: 6, budget: 6, anger: -4, scope: -4 },
  },
  {
    id: 'cashflow-fortress',
    title: 'Boss 材料：现金流护城河',
    unlockHint: '完成长期目标「现金流堡垒」。',
    line: '现金流够厚，博哥敢拒绝不合理低价，预算审判没那么吓人。',
    route: 'business',
    effect: { budget: 10 },
    self: { pressure: -4 },
  },
];

export const CASE_VARIANTS: CaseVariantDefinition[] = [
  {
    id: 'gpu-month-end',
    questId: 'gpu',
    title: '月底追账版',
    condition: '现金低于 500 或预算遗留存在时更常出现。',
    introLine: '财务姐这次不是问账单，是问为什么月底了钱还没回来。',
    winLine: '月底追账落表，博哥把“顺手看看”折成了收款节点。',
    failLine: '月底没收住，财务截图直接变群公告。',
    effect: { anger: 8, budget: -8, trust: -4 },
    route: 'business',
  },
  {
    id: 'gpu-board-report',
    questId: 'gpu',
    title: '老板看板版',
    condition: '商业路线领先时出现。',
    introLine: '客户说账单要给老板看，不能只有一堆数字，要有“云上价值”。',
    winLine: '博哥把账单讲成人话，老板终于知道钱花哪了。',
    failLine: '看板做成玄学海报，客户更不信了。',
    effect: { trust: -6, scope: 8 },
    route: 'delivery',
  },
  {
    id: 'agent-crm-creep',
    questId: 'agent',
    title: 'CRM 顺手版',
    condition: '交付遗留存在时出现。',
    introLine: '老板姐说 Agent 都上线了，CRM、客服、日报不就顺手接一下吗。',
    winLine: '博哥把顺手拆成三张验收单，老板姐沉默了两秒。',
    failLine: '顺手变全量，博哥开始怀疑“今天上线”这四个字。',
    effect: { scope: 12, trust: -6 },
    route: 'delivery',
  },
  {
    id: 'agent-demo-stage',
    questId: 'agent',
    title: '大屏演示版',
    condition: '口碑高于 55 时出现。',
    introLine: '老板姐要拿 Agent 给大老板演示，问能不能整点震撼的。',
    winLine: '演示剧本跑通，震撼有了，范围也没炸。',
    failLine: '大屏一开，需求也跟着投屏放大。',
    effect: { anger: 5, scope: 10, budget: -4 },
    route: 'delivery',
  },
  {
    id: 'sla-group-court',
    questId: 'sla',
    title: '群聊开庭版',
    condition: 'SLA 遗留存在时出现。',
    introLine: '体验姐把两秒延迟截图置顶，群里所有人都开始艾特博哥。',
    winLine: 'SLA 表一贴，群聊从开庭变成排期。',
    failLine: '群聊没压住，客户把“再补一次”说成了判决。',
    effect: { anger: 12, trust: -8 },
    route: 'boundary',
  },
  {
    id: 'sla-vip-room',
    questId: 'sla',
    title: '老板 VIP 房版',
    condition: '周目 2 后出现。',
    introLine: '老板说 VIP 客户不能慢，两秒也不行，半秒最好。',
    winLine: '博哥把 VIP 写进套餐，不再让 SLA 白加班。',
    failLine: 'VIP 变成无限责任，边界直接掉线。',
    effect: { budget: -8, anger: 8, scope: 6 },
    route: 'business',
  },
  {
    id: 'private-audit-night',
    questId: 'private',
    title: '审计夜袭版',
    condition: '合规遗留存在时出现。',
    introLine: '合规姐晚上突然补一份审计清单，说最好明早就有。',
    winLine: '审计清单被拆成可交付包，夜袭变报价。',
    failLine: '清单越补越厚，博哥感觉文档会自己下崽。',
    effect: { scope: 14, anger: 5, trust: -5 },
    route: 'boundary',
  },
  {
    id: 'private-offline-all',
    questId: 'private',
    title: '全离线幻想版',
    condition: '边界训练不足时出现。',
    introLine: '客户说最好完全离线，还要云上一样方便。博哥听完想重启一下人生。',
    winLine: '完全离线被拆成边界清单，幻想终于落地。',
    failLine: '离线幻想扩散，部署文档从一份变三份。',
    effect: { scope: 16, budget: -6 },
    route: 'boundary',
  },
  {
    id: 'cost-free-dashboard',
    questId: 'cost',
    title: '免费大屏版',
    condition: '免费期待遗留存在时出现。',
    introLine: '运营姐说日报都做了，大屏不就是换个展示吗。',
    winLine: '大屏进套餐，日报不再免费繁殖。',
    failLine: '免费大屏一开，售后无限续杯。',
    effect: { budget: -12, scope: 10 },
    route: 'business',
  },
  {
    id: 'cost-threshold-loop',
    questId: 'cost',
    title: '阈值无限改版',
    condition: '成本治理已部分成功时出现。',
    introLine: '客户说阈值可以再灵活一点，最好每个部门都不一样。',
    winLine: '阈值改动变更单落表，灵活终于有价。',
    failLine: '阈值越改越像许愿池。',
    effect: { scope: 12, trust: -4 },
    route: 'business',
  },
  {
    id: 'shadow-fourth-plan',
    questId: 'shadow',
    title: '第四方案陷阱版',
    condition: '影流路线领先时出现。',
    introLine: '采购姐说 A/B/C 都挺好，要不再来个 D 看看。',
    winLine: '博哥说 D 可以，但 D 是变更单。客户突然懂了。',
    failLine: '第四方案一出，前三个方案都不够香了。',
    effect: { scope: 16, anger: 6 },
    route: 'shadow',
  },
  {
    id: 'shadow-rival-copy',
    questId: 'shadow',
    title: '友商复读版',
    condition: '友商低价事件后出现。',
    introLine: '友商也拿三方案来了，客户问你们区别在哪。',
    winLine: 'ShadowBo 把三案讲成三种风险价格，友商低价显得很薄。',
    failLine: '三方案撞车，客户只记住谁便宜。',
    effect: { budget: -10, trust: -8 },
    route: 'shadow',
  },
  {
    id: 'voicebot-refund-gift',
    questId: 'voicebot',
    title: '退款赠品版',
    condition: 'AI 客服失败或交付遗留存在时出现。',
    introLine: '机器人把退款解释成赠品，客户群截图像雪花一样飞。',
    winLine: '退款话术被加护栏，机器人终于不再自信送礼。',
    failLine: '退款继续变赠品，客服姐开始怀疑模型是不是博哥训练的。',
    effect: { anger: 12, trust: -10, scope: 6 },
    route: 'delivery',
  },
  {
    id: 'voicebot-knowledge-hole',
    questId: 'voicebot',
    title: '知识库漏风版',
    condition: '影流或知识库路线推进后出现。',
    introLine: '客户说机器人不是不会答，是每个答案都像开盲盒。',
    winLine: '高频知识先灰度，长尾知识写进第二阶段。',
    failLine: '知识库继续漏风，AI 说得越稳，客户越慌。',
    effect: { trust: -8, scope: 12 },
    route: 'shadow',
  },
  {
    id: 'quota-rival-cut',
    questId: 'quota',
    title: '友商插队价版',
    condition: '友商低价事件或商业路线领先时出现。',
    introLine: '友商说也能给配额，客户问你们贵在哪。',
    winLine: '预留费、排期风险、失败成本一摆，便宜终于显得有点薄。',
    failLine: '客户只听见便宜两个字，算力开始按情绪排队。',
    effect: { budget: -14, trust: -6 },
    route: 'business',
  },
  {
    id: 'quota-midnight-train',
    questId: 'quota',
    title: '半夜开训版',
    condition: '压力高或现金紧张时出现。',
    introLine: '客户说训练任务半夜就开，问能不能先占资源后补流程。',
    winLine: '半夜开训被拆成加急包，资源先占，钱也先到。',
    failLine: '资源先占了，钱没先到，博哥听见现金流裂开的声音。',
    effect: { anger: 8, budget: -10, scope: 8 },
    route: 'business',
  },
  {
    id: 'migration-db-freeze',
    questId: 'migration',
    title: '数据库冻结版',
    condition: 'SLA 遗留或边界训练不足时出现。',
    introLine: '迁移经理说数据库最好不停写，博哥听完沉默三秒。',
    winLine: '冻结窗口、回滚预案和验收点写清，迁移终于不像杂技。',
    failLine: '数据库边写边搬，客户把风险当成售后默认项。',
    effect: { scope: 14, anger: 8, trust: -4 },
    route: 'boundary',
  },
  {
    id: 'migration-license-trap',
    questId: 'migration',
    title: '授权陷阱版',
    condition: '合规遗留存在时出现。',
    introLine: '友商旧授权一打开，客户才发现迁移不是复制粘贴。',
    winLine: '授权、网络、窗口三张表分开，客户终于知道坑在哪。',
    failLine: '授权陷阱没拆开，迁移从三天变成三周开庭。',
    effect: { budget: -8, scope: 12, trust: -6 },
    route: 'boundary',
  },
  {
    id: 'live-kol-surprise',
    questId: 'live',
    title: 'KOL 突然加场版',
    condition: '口碑高或直播客户部分成功后出现。',
    introLine: '老板姐临时请了 KOL，说流量应该也就翻个几倍。',
    winLine: '扩容、降级、客服预案一起上线，KOL 没把博哥带走。',
    failLine: '流量翻倍，告警也翻倍，博哥手机震得像压测工具。',
    effect: { anger: 10, scope: 12, budget: -4 },
    route: 'delivery',
  },
  {
    id: 'live-payment-chain',
    questId: 'live',
    title: '支付链路保命版',
    condition: '预算或压力遗留存在时出现。',
    introLine: '客户说别的都能崩，支付不能崩。博哥想说那得另收钱。',
    winLine: '支付链路单独保级，边缘功能别来抢命。',
    failLine: '支付链路也被顺手进范围，今晚谁都别睡。',
    effect: { scope: 10, trust: -8, anger: 8 },
    route: 'boundary',
  },
  {
    id: 'security-false-positive',
    questId: 'security',
    title: '误报红字版',
    condition: '安全红线事件后出现。',
    introLine: '安全姐说也可能是误报，但今天必须当真。',
    winLine: '误报、真洞、例外说明分三列，红字终于不再一锅炖。',
    failLine: '误报也当真洞修，售后开始替扫描器打工。',
    effect: { scope: 12, budget: -6 },
    route: 'boundary',
  },
  {
    id: 'security-ciso-room',
    questId: 'security',
    title: 'CISO 旁听版',
    condition: '第三幕或合规遗留存在时出现。',
    introLine: 'CISO 坐到会议室后排，所有人说话都开始带审计味。',
    winLine: '红线清单稳住场面，CISO 点头比客户签字还值钱。',
    failLine: 'CISO 没点头，合规红字直接升级成上线门禁。',
    effect: { anger: 10, trust: -8, scope: 8 },
    route: 'boundary',
  },
  {
    id: 'invoice-procurement-loop',
    questId: 'invoice',
    title: '采购流程回环版',
    condition: '采购循环事件或现金低时出现。',
    introLine: '财务说合同没问题，采购说流程没走完，钱在流程里散步。',
    winLine: '报价有效期和付款节点写上，钱终于不再散步。',
    failLine: '流程继续转圈，博哥现金流被绕晕。',
    effect: { budget: -12, anger: 6 },
    route: 'business',
  },
  {
    id: 'invoice-entity-swap',
    questId: 'invoice',
    title: '主体变更版',
    condition: '合同/发票失败后出现。',
    introLine: '客户说主体换了，抬头换了，最好价格别换。',
    winLine: '主体变更进入补充协议，价格也跟着醒了。',
    failLine: '主体换了，钱没换回来，博哥觉得合同在演连续剧。',
    effect: { budget: -10, scope: 8, trust: -4 },
    route: 'business',
  },
  {
    id: 'datapack-dirty-json',
    questId: 'datapack',
    title: '脏 JSON 版',
    condition: '知识库导入失败或压力高时出现。',
    introLine: '十万条数据里混着半截 JSON、截图 OCR 和老板语录。',
    winLine: '清洗、标注、回滚被拆开，数据终于不像垃圾场。',
    failLine: '脏数据灌进知识库，AI 回答开始像喝了两杯。',
    effect: { trust: -10, scope: 12 },
    route: 'shadow',
  },
  {
    id: 'datapack-permission-maze',
    questId: 'datapack',
    title: '权限迷宫版',
    condition: '合规遗留或边界路线领先时出现。',
    introLine: '客户说知识都能导，但不同部门不能互相看，最好今天搞定。',
    winLine: '权限矩阵先落表，知识库不再一上线就泄洪。',
    failLine: '权限迷宫没画清，知识库成了合规炸弹。',
    effect: { scope: 14, anger: 6, budget: -5 },
    route: 'boundary',
  },
  {
    id: 'vip-midnight-call',
    questId: 'vip',
    title: '半夜专属电话版',
    condition: 'VIP 失败或压力高时出现。',
    introLine: 'VIP 老板问半夜能不能直接打给博哥。博哥听见手机先发烫。',
    winLine: '专属电话写进值守包，半夜响铃终于有价格。',
    failLine: '半夜电话没收住，博哥变成人肉网关。',
    effect: { anger: 8, scope: 14, trust: -4 },
    route: 'business',
  },
  {
    id: 'vip-board-seat',
    questId: 'vip',
    title: '老板席旁听版',
    condition: '口碑高或商业路线领先时出现。',
    introLine: '老板席说他们是 VIP，保障要有 VIP 的感觉。',
    winLine: 'VIP 感觉被拆成响应等级、加急费和汇报频率。',
    failLine: 'VIP 感觉变无限责任，博哥觉得自己像云上陪护。',
    effect: { budget: -8, scope: 12, anger: 5 },
    route: 'shadow',
  },
  {
    id: 'boss-budget-trial',
    questId: 'boss',
    title: '预算审判版',
    condition: '预算遗留多时出现。',
    introLine: '联合验收第一问：前面这些免费项，到底谁批的？',
    winLine: '预算审判通过，所有顺手项终于都有归属。',
    failLine: '预算审判没过，免费售后变历史包袱。',
    effect: { budget: -14, anger: 8 },
    route: 'business',
  },
  {
    id: 'boss-sla-trial',
    questId: 'boss',
    title: 'SLA 审判版',
    condition: 'SLA 遗留多时出现。',
    introLine: '验收组翻出两秒截图，说今天别讲感情，讲责任。',
    winLine: 'SLA 审判通过，责任边界终于写明白。',
    failLine: '两秒截图成为传家宝，博哥血压继续上云。',
    effect: { anger: 12, trust: -8 },
    route: 'boundary',
  },
  {
    id: 'boss-shadow-trial',
    questId: 'boss',
    title: '影流审判版',
    condition: '影流路线领先时出现。',
    introLine: '验收组问三套方案到底选哪个，ShadowBo 站在门口开始装没听见。',
    winLine: '三案合一成路线图，客户以为自己选了，其实全在表里。',
    failLine: '影流分身太多，验收组开始数人头。',
    effect: { scope: 14, budget: -6 },
    route: 'shadow',
  },
  {
    id: 'boss-delivery-trial',
    questId: 'boss',
    title: '交付审判版',
    condition: '交付遗留存在时出现。',
    introLine:
      '验收组说 POC、试运行、全量上线你们到底哪个算完，博哥开始找验收清单。',
    winLine: '交付审判通过，满意这两个字终于被拆成能签字的表。',
    failLine: '交付审判没过，客户把“再嗦一次”升级成“再上线一次”。',
    effect: { trust: -12, scope: 8 },
    route: 'delivery',
  },
  {
    id: 'boss-compliance-trial',
    questId: 'boss',
    title: '合规审判版',
    condition: '合规遗留存在时出现。',
    introLine: '合规姐把离线、审计、脱敏三张表摞一块，问这是不是默认包含。',
    winLine: '合规审判通过，材料不是下崽，是分包交付。',
    failLine: '合规审判没过，文档从一份长成了三份，还都急。',
    effect: { scope: 16, budget: -8 },
    route: 'boundary',
  },
  {
    id: 'boss-pressure-trial',
    questId: 'boss',
    title: '强制和解审判版',
    condition: '经营危机或压力遗留存在时出现。',
    introLine: '验收组翻到强制低价和解那页：博哥，你这不是售后，这是情绪分期。',
    winLine: '压力审判通过，博哥把情绪分期改成复盘条款。',
    failLine: '压力审判没过，会议室空气开始按分钟收费。',
    effect: { anger: 10, trust: -10, scope: 6 },
    route: 'boundary',
  },
];

export const EVENTS: EventDefinition[] = [
  {
    id: 'boss-meeting',
    title: '老板临时加会',
    line: '老板说就五分钟，实际烧掉半管耐心。不是，咋又开庭了。',
    effect: { patience: -10, pressure: 7 },
    choices: [
      {
        label: '硬着头皮开',
        line: '会开完了，耐心没了，客户压力也更真实了。',
        effect: { patience: -8, reputation: 3 },
      },
      {
        label: '改成验收表',
        line: '博哥把会变成表，大家突然没那么能发挥了。',
        effect: { boundary: 6, pressure: -4 },
        training: 'sla',
      },
    ],
  },
  {
    id: 'finance-shot',
    title: '财务截图追杀',
    line: '一张账单截图在群里发酵。',
    effect: { reputation: -4, pressure: 9 },
    choices: [
      {
        label: '补成本报表',
        line: '账单梳了一遍，至少不是玄学了。',
        effect: { reputation: 4, pressure: -5 },
        training: 'pricing',
      },
      {
        label: '先别急头白脸',
        line: '博哥稳住了，但预算质疑还在群里冒烟。',
        effect: { patience: 8, pressure: 2 },
      },
    ],
  },
  {
    id: 'compliance',
    title: '合规补材料',
    line: '安全同学加了一行红字。博哥寻思，这也得收钱啊。',
    effect: { boundary: -5, pressure: 8 },
    choices: [
      {
        label: '补材料并标价',
        line: '材料补了，价格也写了。客户沉默，博哥舒服。',
        effect: { cash: 60, boundary: 4 },
        training: 'sla',
      },
      {
        label: '拖到复盘清理',
        line: '先不硬顶，晚上把这锅拆小一点。',
        effect: { energy: 4, pressure: -4 },
        clearIssue: true,
      },
    ],
  },
  {
    id: 'referral',
    title: '客户夸奖转介绍',
    line: '一个客户说“这次还行”，口碑悄悄上涨。',
    effect: { reputation: 8, pressure: -4 },
    choices: [
      {
        label: '做成案例',
        line: '案例一发，信任来得比预算快。',
        effect: { reputation: 6, patience: 4 },
        training: 'delivery',
      },
      {
        label: '顺手要转介绍',
        line: '博哥反手收一个新线索，属于把客气变现金。',
        effect: { cash: 80, pressure: 3 },
        training: 'pricing',
      },
    ],
  },
  {
    id: 'alarm',
    title: '服务器告警',
    line: '监控灯亮了一下，博哥的心也亮了一下。这 b 事儿怎么还没完。',
    effect: { energy: -9, pressure: 8 },
    choices: [
      {
        label: '立刻降级',
        line: '服务降级但口碑保住了，SLA 没开庭。',
        effect: { energy: -5, reputation: 4, pressure: -6 },
        training: 'sla',
      },
      {
        label: '影流排查',
        line: 'ShadowBo 分三路看日志，快是快，就是有点费人。',
        effect: { patience: -4, pressure: -10 },
        training: 'shadow',
      },
    ],
  },
  {
    id: 'rival',
    title: '友商低价搅局',
    line: '友商报价像从地板里钻出来。',
    effect: { reputation: -5, pressure: 6 },
    choices: [
      {
        label: '报价分层',
        line: '低价归低价，旗舰归旗舰，别混一张表。',
        effect: { cash: 50, boundary: 3 },
        training: 'pricing',
      },
      {
        label: '拿交付说话',
        line: '博哥不吵价格，直接亮验收路径。',
        effect: { reputation: 5, patience: -3 },
        training: 'delivery',
      },
    ],
  },
  {
    id: 'shadow-idea',
    title: '影流灵感爆发',
    line: 'ShadowBo 在脑内递出第三套方案。',
    effect: { patience: 6, pressure: -5 },
    choices: [
      {
        label: '排练三方案',
        line: 'A/B/C 都有价格，客户以为自己赢了。',
        effect: { patience: 4, pressure: -4 },
        training: 'shadow',
      },
      {
        label: '别整太花',
        line: '今天先做人，明天再影流。',
        effect: { energy: 8, boundary: 2 },
      },
    ],
  },
  {
    id: 'quiet-review',
    title: '博哥收工复盘',
    line: '关门以后，真正的售后才开始变强。再有人说顺手，就写进合同。',
    effect: { energy: 8, patience: 8, pressure: -8 },
    choices: [
      {
        label: '清一个遗留',
        line: '博哥把一个烂摊子写成复盘项，明天少背一口锅。',
        effect: { pressure: -6, patience: 4 },
        clearIssue: true,
      },
      {
        label: '练一遍话术',
        line: '这单咋收钱，先说人话，再说价格。',
        effect: { boundary: 3, energy: 3 },
        training: 'recovery',
      },
    ],
  },
  {
    id: 'poc-creep',
    title: 'POC 变全量',
    line: '客户说 POC 跑通了，那全量上线不就顺手吗？博哥听完血压有点云原生。',
    effect: { patience: -8, pressure: 8 },
    choices: [
      {
        label: '拆成里程碑',
        line: '一拆三段，客户终于发现顺手也有排期。',
        effect: { pressure: -5, reputation: 3 },
        training: 'delivery',
      },
      {
        label: '先守体力',
        line: '今天不硬刚，别把自己说干。',
        effect: { energy: 8, reputation: -2 },
      },
    ],
  },
  {
    id: 'sla-court',
    title: '群聊 SLA 开庭',
    line: '两秒延迟截图被置顶，客户开始在群里点名。几把的，又开始了。',
    effect: { patience: -9, pressure: 10 },
    choices: [
      {
        label: '贴出 SLA 表',
        line: '表一贴，群里安静半分钟。半分钟也是胜利。',
        effect: { boundary: 5, pressure: -6 },
        training: 'sla',
      },
      {
        label: '先降级保命',
        line: '服务稳住了，博哥少活三分钟。',
        effect: { energy: -4, reputation: 5 },
      },
    ],
  },
  {
    id: 'invoice-lost',
    title: '发票抬头迷路',
    line: '财务姐说抬头不对，合同不对，价格也不对。三不对，博哥一口气没上来。',
    effect: { cash: -40, pressure: 7 },
    choices: [
      {
        label: '补报价附件',
        line: '附件补上，钱没立刻回来，但锅小了。',
        effect: { cash: 30, pressure: -3 },
        training: 'pricing',
      },
      {
        label: '认栽重开',
        line: '这单先认，晚上复盘别再犯。',
        effect: { patience: 5, cash: -30 },
        training: 'recovery',
      },
    ],
  },
  {
    id: 'security-redline',
    title: '安全红线',
    line: '安全同学把“必须”改成“必须立刻”，博哥寻思这字是不是会自己繁殖。',
    effect: { boundary: -7, pressure: 9 },
    choices: [
      {
        label: '列红线清单',
        line: '能做、不能做、加钱做，三列落表。',
        effect: { boundary: 7, pressure: -5 },
        training: 'sla',
      },
      {
        label: '拉合规会审',
        line: '人多了，锅分薄了，但会也变长了。',
        effect: { patience: -4, reputation: 4 },
        training: 'delivery',
      },
    ],
  },
  {
    id: 'ceo-demo',
    title: '老板要大屏演示',
    line: '老板姐说今天下午给大老板看，问能不能整点震撼的。博哥：震撼也得有验收环境。',
    effect: { energy: -8, pressure: 9 },
    choices: [
      {
        label: '做演示剧本',
        line: '大词少说，场景跑通。客户终于看懂一点。',
        effect: { reputation: 5, pressure: -4 },
        training: 'delivery',
      },
      {
        label: '影流造氛围',
        line: 'ShadowBo 递了三套演示词，震撼是震撼，贵也是真贵。',
        effect: { cash: 60, pressure: 2 },
        training: 'shadow',
      },
    ],
  },
  {
    id: 'procurement-loop',
    title: '采购循环砍价',
    line: '采购姐说不是不给钱，是流程还要再走一遍。博哥听见“再一遍”就闹心。',
    effect: { cash: -30, pressure: 6 },
    choices: [
      {
        label: '设报价有效期',
        line: '价格不是天气预报，不能每天刷新。',
        effect: { cash: 70, boundary: 3 },
        training: 'pricing',
      },
      {
        label: '换试运行合同',
        line: '先小单锁住，再谈大单。',
        effect: { reputation: 4, cash: 30 },
        training: 'delivery',
      },
    ],
  },
  {
    id: 'shadow-overfit',
    title: '影流过拟合',
    line: '三套方案写太满，客户开始问第四套。ShadowBo 沉默了。',
    effect: { pressure: 10, patience: -5 },
    choices: [
      {
        label: '砍回三档',
        line: 'A/B/C 是选择，不是许愿池。',
        effect: { boundary: 5, pressure: -6 },
        training: 'shadow',
      },
      {
        label: '拉表收口',
        line: '再问就是变更单。客户听完表情稳定了。',
        effect: { boundary: 7, reputation: -1 },
        training: 'sla',
      },
    ],
  },
];
