#!/usr/bin/env node
import { readFileSync } from 'node:fs';

const prologue = readFileSync(
  'apps/frontend-astro/src/game/yuanbo/prologue.ts',
  'utf8',
);
const page = readFileSync(
  'apps/frontend-astro/src/pages/bo/yuanbo-game.astro',
  'utf8',
);

const requiredStrings = [
  '第一天：这姐咋收钱啊',
  '财务姐：GPU 账单爆炸',
  '财务姐追问：谁批的预算',
  '老板上线拆板：今天上线怎么说',
  '上线彩排：别把小范围试点吹成全部上线',
  '客户姐：再给我梳一次',
  '客户反悔拆板：免费、上线、拉倒',
  '收费谈判：这姐咋收钱啊',
  '报价上桌',
  '补一次',
  '签范围',
  '体面拉倒',
  '先回财务：钱不能糊',
  '先回老板：上线别吹满',
  '先回客户：我先听你说',
  'opening:finance',
  'opening:boss',
  'opening:customer',
  '结局：收到钱',
  '结局：补一次',
  '结局：体面拉倒',
  '结局：免费干崩',
  'SpeakerProfile',
  'speaker-finance',
  'speaker-boss',
  'speaker-customer',
  'EvidenceOption',
  'evidenceForecast',
  '终幕报价时预算更稳',
  '终幕补一次时',
  '终幕需求变多时',
  '终幕拉倒时更体面',
  'PrepOption',
  'PrepWorkbenchCard',
  'STARTING_TIME',
  'timeLeft',
  'timeLog',
  'showPrepMenu',
  'showPrepWorkbench',
  'prepWorkbenchCards',
  'rehearsal-workbench',
  'drawPrepWorkbenchStatus',
  'drawPrepWorkbenchCards',
  'prepWorkbench',
  'spendTime',
  '战前准备',
  '演练收费说法',
  '跑一遍小范围试点演示',
  '写拉倒台阶',
  'prepForecast',
  '克制预算质疑',
  '克制顺手加范围',
  '克制不签范围的僵局',
  'prepSummary',
  'timeSpendSummary',
  'SCENE_CUES',
  'SCENE_EVENTS',
  'StorySetPiece',
  'StageComposition',
  'stageComposition',
  'drawStageComposition',
  'stageComposition:',
  '三条事故同时进门',
  '玩家不是在逛办公室',
  '博哥要做：',
  'SceneMemoryProp',
  'drawStorySetPiece',
  'drawSceneMemoryProps',
  'storySetPieceForBeat',
  'sceneMemoryProps',
  'storySetPiece',
  'sceneMemoryProps',
  '上午账单',
  '上线说法',
  '客户边界',
  '财务账单墙',
  '上线玻璃房',
  '客户收费桌',
  'SceneEventBubble',
  'sceneEvents',
  'activeActorBarks',
  'actorBarks',
  'boThoughtLine',
  'boThoughtPlacement',
  'boThought',
  'boThoughtBox',
  '先别回可以。',
  '补一次别补全世界。',
  '先回客户，钱谁认？',
  '试点上线，能播。',
  '全部上线怎么算钱？',
  'OPENING_INBOX',
  'OPENING_INBOX_CHOICES',
  'OpeningInboxChoice',
  'OpeningInboxItem',
  'OpeningMessageTarget',
  'openingMessageTargets',
  'chooseOpeningMessage',
  'showOpeningInboxBoard',
  'drawOpeningInboxBoardCards',
  'opening-inbox-board',
  'openingInboxBoard',
  'openingTargets',
  '点击回复',
  'drawOpeningInbox',
  'drawWakeOffice',
  'drawWakeHud',
  'openingInbox',
  'openingScene',
  '工位亮屏',
  "cue.prop === 'messages') return",
  "state.beat === 'wake'",
  '09:17 / 工位亮屏',
  '博哥工位：三条未读',
  'LedgerSortItem',
  'LedgerSortSlot',
  'LEDGER_SORT_ITEMS',
  '账单拆包：把截图贴到正确格子',
  'ticket-slot-board',
  'drawLedgerSortSlots',
  'drawLedgerSortTickets',
  'ledgerSorting',
  'completeLedgerSorting',
  'BattleDuelFocus',
  'battleDuelFocus',
  'duelFocus',
  '本回合对峙',
  'BattleClosingGoal',
  'battleClosingGoals',
  'drawBattleClosingGoals',
  '收桌目标',
  'closingGoals',
  '体面拉倒',
  'CustomerJokeFragment',
  'CUSTOMER_JOKE_FRAGMENTS',
  'CustomerJokeRoute',
  'CUSTOMER_JOKE_ROUTES',
  '客户语音拆句：报价、补偿、拉倒',
  'voice-fragment-board',
  'drawCustomerJokeFragments',
  'drawCustomerJokeRoutes',
  'customerJokeBoard',
  'CustomerReversalPressure',
  'CUSTOMER_REVERSAL_PRESSURES',
  'CustomerReversalRoute',
  'CUSTOMER_REVERSAL_ROUTES',
  '客户反悔拆板：免费、上线、拉倒',
  'reversal-pressure-board',
  'drawCustomerReversalPressures',
  'drawCustomerReversalRoutes',
  'customerReversalBoard',
  'BossLaunchPressure',
  'BOSS_LAUNCH_PRESSURES',
  'BossLaunchRoute',
  'BOSS_LAUNCH_ROUTES',
  '老板上线拆板：今天上线怎么说',
  'launch-pressure-board',
  'drawBossLaunchPressures',
  'drawBossLaunchRoutes',
  'bossLaunchBoard',
  'drawSceneEventBubbles',
  'sceneEventColor',
  'hotspotSceneVisible',
  'hotspotVisualSnapshots',
  'hidden-clue-zone',
  'readClue',
  'visualTarget',
  'GuideTarget',
  'currentGuideTarget',
  'directionArrow',
  'targetGuide',
  'updateTargetGuide',
  'setClickTarget',
  'clearClickTarget',
  'clickMoveActive',
  'pendingInteraction',
  'approachActor',
  'approachHotspot',
  'tryPendingInteraction',
  'actorApproachOffset',
  '点击地面或 WASD 移动',
  '目标：',
  '财务群',
  '客户语音',
  '现场冲突',
  '三群同时炸',
  '账单拍桌',
  '顺手全部上线',
  'DebtId',
  '遗留问题生成',
  '遗留问题带入',
  'budget-blame',
  'full-launch',
  'debtSummary',
  '现场反应',
  'ChoiceOutcomeCard',
  'outcomeCard',
  'outcomeSceneChange',
  'outcomeFinalImpact',
  '桌上变化',
  'DecisionVignette',
  'decisionVignette',
  'ActionForecast',
  'ManagementHint',
  'dialogManagementHint',
  'shouldShowManagementHint',
  'managementGapLine',
  'choiceManagementRecommendation',
  'actionForecastCost',
  'forecast',
  'makeChoiceCard',
  'makeManagementHintCard',
  'choiceForecasts',
  'managementHint',
  '今日账本：',
  '当前缺口：',
  '建议：',
  'touchBridgeHidden',
  'setTouchBridgeHidden',
  '当场变化：',
  '代价：',
  '晚上用得上：',
  'routeEndgameLine',
  'drawOutcomeQuote',
  'drawOutcomeChips',
  '晚上回响',
  '复盘：',
  '谈判阶段突破',
  'showBattlePhaseBreak',
  'PhaseBreakCard',
  'PhaseBreakPanel',
  'phaseBreakPanels',
  'phaseBreakChips',
  'drawPhaseBreakChips',
  '客户让步',
  '桌面变化',
  '下一问',
  'phaseBreakCard',
  'phaseBreakStory',
  'phaseBreakNextGoal',
  '赢法：',
  '把“再梳一次”写成小范围试点',
  'ClientIntentType',
  'BATTLE_SKILLS',
  'skillPreview',
  'nextClientIntent',
  'suggestedSkillsForIntent',
  'battlePhaseLine',
  'skillTableLine',
  'BattleCommand',
  'battleCommandCards',
  'drawBattleCommandCard',
  'battleSkillSpeechLine',
  'battleSkillRiskLine',
  'skillCommands',
  '本回合对峙',
  '克制：',
  'BattleTurnBeat',
  'BattleTableProp',
  'NegotiationTableLines',
  'drawNegotiationTableScene',
  'drawBattleTableProps',
  'drawNegotiationTokens',
  'negotiationTableLines',
  'negotiationTokens',
  'battleTableProps',
  '谈判桌',
  'tableLines',
  'tableTokens',
  'tableProps',
  'sceneMode',
  'meeting-table',
  'drawBattleDuelFocus',
  'battleTurnBeat',
  '客户压上来',
  '博哥先想',
  'choiceSpeechLine',
  '博哥说',
  '当场变化',
  '代价：',
  '客户压上来',
  'turnBeat',
  'StoryPressure',
  'storyPressureFor',
  '今日追问',
  '财务账单没钉死',
  '老板今天上线承诺',
  '拉倒先上桌',
  'battleCounterSkills',
  '说法对路',
  '博哥还没回',
  'skillPreviews',
  'lastImpact',
  'battleImpact',
  'battleDeltaSummary',
  '路线徽章',
  'drawEndingScoreChips',
  "state.decisions.includes('customerReversal:walkaway-line')",
  'battle.client.scope <= 42',
  'routeReport',
  '路线称号',
  'EndingEcho',
  'endingEchoes',
  'drawEndingClosingScene',
  'endingClosingSceneLine',
  'endingScene',
  '会议室收工',
  '账单',
  '范围单',
  '试点记录',
  "speaker: 'finance'",
  "speaker: 'boss'",
  "speaker: 'customer'",
  '报价上桌型售后王',
  '边界合同人',
  '免费售后受害者',
  'metricDeltaParts',
  '钱先有名',
  '关系变冷',
  '边界更清楚',
  'debtDiffSummary',
  '遗留问题变化',
  'GPU 峰值曲线',
  '小范围试点验收句',
  '拉倒留证据',
  'evidenceSummary',
  'exportCode',
  'importCode',
  'storageKey',
  'encodeSave',
  'decodeSave',
  'StoryBeatCard',
  'clock:',
  'place:',
  'STORY_BEATS',
  '09:17',
  '09:32',
  '10:42',
  '11:30',
  '12:18',
  '14:20',
  '15:05',
  '16:00',
  '19:40',
  '时间地点：',
  '剩余行动：',
  'MilestoneId',
  'MILESTONES',
  'milestoneSummary',
  'storyCausalChain',
  'storyCausalLine',
  '今日因果',
  'causalChain',
  'causalLine',
  '钱：报价上桌',
  '上线：只承诺小范围试点',
  '客户：补一次锁进小范围试点',
  '章节推进',
  'drawFloorActTrail',
  'drawSceneMask',
  'drawHudStoryRail',
  'mapHudMode',
  'chapter-strip',
  'compact-map',
  'drawHudCausalStrip',
  '今日走势',
  'storyCard',
  'BeatBridge',
  'BEAT_BRIDGES',
  '镜头转场',
  '上桌前清单',
  'battleDossierLines',
  'storyboard',
  '博哥心声',
  'showBeatBridge',
  'BridgeStoryboardPanel',
  'bridgeStoryboardPanels',
  'drawBridgeStoryboard',
  '刚才留下的余波',
  '博哥心里过一遍',
  '下一幕压力',
  'bridgeCard',
  '现场冲突',
  'zoneOutcomeLabel',
  'zoneOutcomes',
  '试点上线',
  '体面拉倒',
  '当前冲突',
  '__YUANBO_PROLOGUE_QA__',
  'bo-chaos:yuanbo-first-day-prologue:v1',
];

const requiredFlow = [
  "beat: 'wake'",
  "beat: 'finance'",
  "beat: 'financeAudit'",
  "beat: 'boss'",
  "beat: 'bossRehearsal'",
  "beat: 'customer'",
  "beat: 'customerReversal'",
  "state.beat = 'battle'",
  "state.beat = 'ending'",
  "state.beat = nextBeat",
  "decision: 'opening:finance'",
  "this.applyStoryChoice(choice.decision, 'finance')",
  "this.applyStoryChoice('finance:quote', 'financeAudit')",
  "this.applyStoryChoice('financeAudit:paid-pilot', 'boss')",
  "decision: 'boss:poc'",
  "this.applyStoryChoice(route.decision, 'bossRehearsal')",
  "this.applyStoryChoice('bossRehearsal:poc-script', 'customer')",
  "this.applyStoryChoice(route.decision, 'customerReversal')",
  "this.chooseCustomerReversal(",
  "'customerReversal:poc-only'",
  "state.mode = 'ending'",
];

const missing = [...requiredStrings, ...requiredFlow].filter(
  (needle) => !prologue.includes(needle),
);
if (missing.length) {
  console.error('yuanbo prologue probe failed: missing story markers');
  missing.forEach((item) => console.error(`- ${item}`));
  process.exit(1);
}

if (!page.includes("../../game/yuanbo/prologue")) {
  console.error('yuanbo prologue probe failed: Astro page is not using prologue entry');
  process.exit(1);
}

const choiceCount = (prologue.match(/label: '/g) || []).length;
const endingCount = (prologue.match(/Ending/g) || []).length;
if (choiceCount < 27 || endingCount < 3) {
  console.error(
    `yuanbo prologue probe failed: weak branching surface choices=${choiceCount} endingRefs=${endingCount}`,
  );
  process.exit(1);
}

console.log(
  `yuanbo prologue probe passed: story markers=${requiredStrings.length}, flow markers=${requiredFlow.length}, choices=${choiceCount}`,
);
