# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Pnpm CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "17 18 * * *"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Refresh Lighthouse activities
      if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
      run: pnpm run update:lighthouse-news
      
    - name: Verify
      env:
        ASTRO_SENTRY_AUTH_TOKEN: ${{ secrets.ASTRO_SENTRY_AUTH_TOKEN }}
      run: pnpm run verify

    # 添加打包步骤
    - name: Archive production artifacts
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        cd apps/frontend-astro
        find dist -type f -name "*.map" -delete
        tar -czf dist.tar.gz dist/

    # 添加上传步骤
    - name: Upload to server
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        cd apps/frontend-astro
        curl --fail --show-error --connect-timeout 30 --max-time 1800 --retry 2 --retry-delay 15 -X POST https://yuanbo.online/oss_service/upload \
          -F "file=@dist.tar.gz" \
          -F "path=retire" \
          -F "should_unzip=true" \
          -F "token=${{ secrets.OSS_RS_UPLOAD_TOKEN }}"
